---@meta
-- Engine globals outside the reactive layer, and the restricted `os` (ADR-0048).
-- Generated by `just stubs` from each global's Rust signature and `///` docs (`lua::luacats`).
-- The VM has no `io`, `debug` or FFI. `dofile` and `loadfile` remain and block on file I/O.

---[docs](https://anasgets111.github.io/mantle/guide/runtime.html#the-vm)
---Only these four calls exist; the rest of `os` is removed (ADR-0048).
---@class oslib
os = {}

---@param format? string `strftime` directives, default `"%c"`; `"*t"` returns a table. A leading `!` reads UTC.
---@param time? integer Unix seconds, default now.
---@return string|table
function os.date(format, time) end

---@param t? table An `os.date("*t")`-shaped table, default now.
---@return integer # Unix seconds, wall clock.
function os.time(t) end

---@return number # CPU seconds this process has used; not elapsed time.
function os.clock() end

---@param name string
---@return string? # The shell's environment variable, `nil` when unset.
function os.getenv(name) end

---Declares what `mantle call <name> [args...]` runs (ADR-0197). Each argument arrives JSON-decoded,
---or as a string when it is not JSON. The return prints as JSON (≤ 1 MiB), a string bare and `nil`
---as nothing; a raise or an unconvertible return fails the call. Runs under the 5 ms CPU budget.
---Every evaluation clears all actions, so declare at the top level.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#action)
---@param name string Non-empty and unique per evaluation, else raises. Opaque: nothing splits on `.`.
---@param handler fun(...: any): any?
function action(name, handler) end

json = {}

---Decodes JSON and never raises: failure returns `nil, message`. JSON `null` also decodes to `nil`,
---and a `null` array element leaves a hole that stops `ipairs` (ADR-0057). There is no encoder.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#jsondecode)
---@param text string
---@return any value
---@return string? error
function json.decode(text) end

log = {}

---Writes a stamped line at this level, arguments joined like `print`'s (ADR-0245). Every level
---prints by default; filter with `MANTLE_LOG=config=warn` or `config=off`.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#log)
---@param ... any
function log.error(...) end

---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#log)
---@param ... any
function log.warn(...) end

---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#log)
---@param ... any
function log.info(...) end

---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#log)
---@param ... any
function log.debug(...) end

---Declares the font fallback chain. Each glyph falls back across it, so one chain covers body text,
---CJK and emoji; a `text` node's `font` goes in front of it (ADR-0144). Read once at startup: a
---change needs a shell restart (ADR-0043). The last call wins.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#fonts)
---@param chain string[] Family names. The first is the body face and the only one whose bold and italic load; the rest cover glyphs it lacks. A hole, a named key or a non-string raises; an uninstalled family is skipped and logged at `-vvv`. Never calling it keeps `sans-serif`, Noto Sans CJK JP, Noto Color Emoji.
function fonts(chain) end

---fzf's score for `needle` in `haystack`, or `nil, nil` when its characters do not appear in order
---(ADR-0201). Smart case: one uppercase character in `needle` makes the match case-sensitive.
---Scores compare only against the same needle; non-ASCII input takes a cruder scorer.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#fuzzy)
---@param haystack string Non-UTF-8 bytes score as no match.
---@param needle string Empty scores `0, 0`.
---@return integer? score
---@return integer? start 0-based byte offset of the needle's first character at its earliest in-order hit (the best-scoring one for a one-character needle). For tiebreaks, not highlighting.
function fuzzy(haystack, needle) end

---@class SessionProcessHandle
---A program declared with `session_process`. Each field is a signal over its `mantle.processes`
---entry, `nil` before the first push; while `running` is false they describe the finished run.
---@field running Signal<boolean?> Whether it is up.
---@field pid Signal<integer?> Also its process group id. Kept after exit; `nil` before a spawn or after a failed `start`.
---@field started_at Signal<integer?> Unix seconds the current or last run began; `nil` before a spawn or after a failed `start`.
---@field exit_code Signal<integer?> The last finished run's exit status; `nil` while running, before the first run, or after a signal ended it.
---@field start_error Signal<string?> Why the last `start` spawned nothing, usually a command not on `PATH`; `""` when it spawned.
local SessionProcessHandle = {}

---Starts the program unless it is already running, with stdio inherited. The outcome arrives as
---state: `running`, or `start_error`.
---@param cmd string Looked up on `PATH`; no shell, so no globbing, pipes or quoting.
---@param args? string[] Already split: `"a b"` is one argument.
function SessionProcessHandle:start(cmd, args) end

---Sends `signal` to the program itself, not its group. A no-op when it is not running.
---@param signal SignalName
function SessionProcessHandle:signal(signal) end

---Sends the declared `stop_signal` to the program's group, then `SIGKILL` 5 s later. Shell
---shutdown does this to every session process.
function SessionProcessHandle:stop() end

---Declares a program that lives for the session: the Supervisor holds it across reloads and stops
---it at shutdown. Re-declaring a name returns the same handle and re-reads only `stop_signal`, so
---declare at a module's top level. Use `process.run` when you need its output.
---[docs](https://anasgets111.github.io/mantle/guide/processes.html#session_process)
---@param spec { name: string, stop_signal?: SignalName, [string]: "no such property" } `name` keys it in `mantle.processes`; empty raises. `stop_signal` defaults to `"TERM"`.
---@return SessionProcessHandle
function session_process(spec) end

---@class TimerHandle
local TimerHandle = {}

---Disarms the timer. A no-op once it has fired or been cancelled, and inside its own callback.
function TimerHandle:cancel() end

---Runs `callback` once, `ms` from now, on a monotonic clock, under the 5 ms CPU budget (ADR-0203).
---Repeat by re-arming inside `callback`. Every evaluation clears all timers, so arm at the top level;
---a discarded handle still fires.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#timer)
---@param ms integer `[1, 86400000]`; outside raises.
---@param callback fun() A raise is logged as a warning.
---@return TimerHandle
function timer(ms, callback) end

process = {}

---@class ProcessHandle
local ProcessHandle = {}

---`SIGTERM` to its process group, `SIGKILL` 100 ms later; `exit_cb` still fires. A no-op after exit.
function ProcessHandle:kill() end

---Spawns `cmd` with stdout and stderr piped and stdin on `/dev/null`, without blocking (ADR-0026).
---The process belongs to the evaluation: a reload kills its group and calls `exit_cb(nil)`.
---Callbacks run unbudgeted; a raise is logged as a warning.
---[docs](https://anasgets111.github.io/mantle/guide/processes.html#processrun)
---@param cmd string Looked up on `PATH`; no shell, so no globbing, pipes or quoting.
---@param args string[] Already split: `"a b"` is one argument.
---@param out_cb fun(line: string, stream: "stdout"|"stderr") Once per line, newline stripped, cut at 64 KiB. Accumulate here and decode in `exit_cb`.
---@param exit_cb fun(code: integer?) `nil` when a signal ended it or it failed to spawn.
---@return ProcessHandle
function process.run(cmd, args, out_cb, exit_cb) end

---Spawns `cmd` in its own session with stdio on `/dev/null`; it outlives every reload and the
---shell. No handle, output or exit code, and a spawn failure is only logged (ADR-0188).
---[docs](https://anasgets111.github.io/mantle/guide/processes.html#processdetach)
---@param cmd string Looked up on `PATH`; no shell, so no globbing, pipes or quoting.
---@param args string[] Already split: `"a b"` is one argument.
function process.detach(cmd, args) end

palette = {}

---@class PaletteSwatch
---@field color Color `#RRGGBB`.
---@field share number Fraction of the counted (non-transparent) pixels, 0 to 1.

---@class PaletteHandle
local PaletteHandle = {}

---Drops the callback. The decode still finishes.
function PaletteHandle:cancel() end

---Extracts an image's dominant colours off the Lua thread (ADR-0249). `cb` gets them most common
---first, or `nil` on failure (logged). `cb` runs unbudgeted.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#palettequantize)
---@param path string A local raster file; no SVG or URL.
---@param opts? { depth?: integer, rescale?: integer, [string]: "no such property" } `depth` 0 to 8, default 3: up to `2^depth` colours. `rescale` caps the longest edge before counting, default 128, `0` for full size. Out of range raises.
---@param cb fun(swatches: PaletteSwatch[]?)
---@return PaletteHandle
function palette.quantize(path, opts, cb) end
