---@meta
-- Engine globals outside the reactive layer, and the restricted `os` (ADR-0048).
-- Generated by `just stubs` from each global's Rust signature and `///` docs (`lua::luacats`).
-- The VM has no `io`, `debug`, FFI, `dofile` or `loadfile`.

---[docs](https://anasgets111.github.io/mantle/guide/runtime.html#the-vm)
---Only these four calls exist; the rest of `os` is removed (ADR-0048).
---@class oslib
os = {}

---@param format? string `strftime` directives, default `"%c"`; `"*t"` returns a table. A leading `!` reads UTC.
---@param time? integer Unix seconds, default now.
---@return string|table
function os.date(format, time) end

---@param t? table An `os.date("*t")`-shaped table, default now.
---@return integer # Unix seconds, wall clock.
function os.time(t) end

---@return number # CPU seconds this process has used; not elapsed time.
function os.clock() end

---@param name string
---@return string? # The shell's environment variable, `nil` when unset.
function os.getenv(name) end

---Declares what `mantle call <name> [args...]` runs (ADR-0197). Each argument arrives JSON-decoded,
---or as a string when it is not JSON. The return prints as JSON (≤ 1 MiB), a string bare and `nil`
---as nothing; a raise or an unconvertible return fails the call. Runs under the Lua CPU budget.
---Every evaluation clears all actions, so declare at the top level.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#action)
---@param name string Non-empty and unique per evaluation, else raises. Opaque: nothing splits on `.`.
---@param handler fun(...: any): any?
function action(name, handler) end

json = {}

---Decodes JSON and never raises: failure returns `nil, message`. JSON `null` also decodes to `nil`,
---and a `null` array element leaves a hole that stops `ipairs` (ADR-0057).
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#jsondecode)
---@param text string
---@return any value
---@return string? error
function json.decode(text) end

---Encodes a value as compact JSON with sorted keys. A table with only positive integer keys is an
---array, so `{}` is `[]`, and a hole inside it is `null`; other tables need string keys. Raises
---on a function, userdata, cycle, NaN, infinity, nesting past 127, over 2^20 values, an array over
---half holes or a decoded array given a named key.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#jsonencode)
---@param value any Tables, strings, numbers, booleans and `nil`.
---@return string
function json.encode(value) end

log = {}

---Writes a stamped line at this level, arguments joined like `print`'s (ADR-0245). Every level
---prints by default; filter with `MANTLE_LOG=config=warn` or `config=off`.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#log)
---@param ... any
function log.error(...) end

---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#log)
---@param ... any
function log.warn(...) end

---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#log)
---@param ... any
function log.info(...) end

---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#log)
---@param ... any
function log.debug(...) end

---Declares the font fallback chain. Each glyph falls back across it, so one chain covers body text,
---CJK and emoji; a `text` node's `font` goes in front of it (ADR-0144). Read once at startup: a
---change needs a shell restart (ADR-0043). The last call wins.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#fonts)
---@param chain string[] Family names. The first is the body face and the only one whose bold and italic load; the rest cover glyphs it lacks. A hole, a named key or a non-string raises; an uninstalled family is skipped and logged at `-vvv`. Never calling it keeps `sans-serif`, Noto Sans CJK JP, Noto Color Emoji.
function fonts(chain) end

---fzf's score for `needle` in `haystack`, or `nil, nil` when its characters do not appear in order
---(ADR-0201). Smart case: one uppercase character in `needle` makes the match case-sensitive.
---Scores compare only against the same needle; non-ASCII input takes a cruder scorer.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#fuzzy)
---@param haystack string Non-UTF-8 bytes score as no match.
---@param needle string Empty scores `0, 0`.
---@return integer? score
---@return integer? start 0-based byte offset of the needle's first character at its earliest in-order hit (the best-scoring one for a one-character needle). For tiebreaks, not highlighting.
function fuzzy(haystack, needle) end

---@class FocusHandle
---A named focus target: a plain textfield or a focusable control.
local FocusHandle = {}

---Give this field or control the keyboard after the current callback updates its surface. Works from
---`on_click`, `on_key` and edits typed or committed into a field (`on_change`, `on_submit`,
---`on_cancel`); elsewhere it does nothing, as in the `on_change` an `autofocus` or `set_text` fires.
---A key callback's request shows the focus outline.
function FocusHandle:request() end

---Sets the text of every plain textfield with this name and an `on_change` or `on_submit`, hidden ones
---too: caret at the end, undo and composition cleared, no `on_change`. Does nothing on a control. Raises
---on control characters other than `\n` or over 64 KiB; a single-line field refuses a `\n` with a
---warning and keeps its text. Applies when the callback returns.
---@param text string
function FocusHandle:set_text(text) end

---Names a plain textfield or focusable control that `:request()` can focus from a click or key callback.
---[docs](https://anasgets111.github.io/mantle/guide/input.html#text-fields)
---@param name string Shared with the node's `focus_target` property.
---@return FocusHandle
function focus_target(name) end

---The edges a tiling compositor has tiled the window against.
---@class ToplevelTiled
---@field left boolean
---@field right boolean
---@field top boolean
---@field bottom boolean

---The most room the compositor suggests for the window, in logical pixels.
---@class ToplevelBounds
---@field width integer
---@field height integer

---What the compositor can do for the window; a compositor that never says supports everything.
---@class ToplevelCapabilities
---@field window_menu boolean
---@field maximize boolean
---@field fullscreen boolean
---@field minimize boolean

---What the compositor last configured a `window` to be. Before the first configure and after the window closes it is the default: nothing set, `decoration = "client"`.
---@class ToplevelState
---@field activated boolean The window has keyboard focus as the compositor sees it.
---@field maximized boolean
---@field fullscreen boolean
---@field resizing boolean An interactive resize is under way.
---@field tiled ToplevelTiled
---@field bounds? ToplevelBounds `nil` until the compositor suggests bounds.
---@field capabilities ToplevelCapabilities
---@field decoration "server"|"client" Who draws the frame: the mode the compositor chose, which is `"client"` without `zxdg_decoration_manager_v1`.

---@class ToplevelHandle
---A named `window` the app draws its own frame for. `move`, `resize` and `show_menu` ask the compositor to take over the pointer, and only work inside an `on_press` or `on_drag` `"start"` callback; elsewhere, on a hidden window or on another surface's press, they log a warning and do nothing. `set_maximized`, `set_minimized` and `set_fullscreen` work from any callback; the compositor decides, and the result arrives through `state()`.
local ToplevelHandle = {}

---Start an interactive move of the window, as dragging a title bar does.
function ToplevelHandle:move() end

---Start an interactive resize from an edge or corner of the window.
---@param edge string `"top"`, `"bottom"`, `"left"`, `"right"`, `"top_left"`, `"top_right"`, `"bottom_left"` or `"bottom_right"`.
function ToplevelHandle:resize(edge) end

---Open the compositor's window menu at the pointer's press position.
function ToplevelHandle:show_menu() end

---Ask the compositor to maximize the window, or to restore it with `false`.
---@param maximized boolean
function ToplevelHandle:set_maximized(maximized) end

---Ask the compositor to minimize the window; there is no request to undo it.
function ToplevelHandle:set_minimized() end

---Ask the compositor to make the window fullscreen on its current output, or to restore it with `false`.
---@param fullscreen boolean
function ToplevelHandle:set_fullscreen(fullscreen) end

---The window's configure state as a read-only signal, rewritten when the compositor changes it, so a frame can follow `activated`, `maximized`, `tiled` and the like. Reading it never requests a change.
---@return Signal<ToplevelState>
function ToplevelHandle:state() end

---Names a `window` whose frame the app draws; call `:move()`, `:resize(edge)` or `:show_menu()` on it from an `on_press`, or `:state()` for its configure state.
---[docs](https://anasgets111.github.io/mantle/surfaces/window.html#custom-title-bar)
---@param id string The `id` of a `window`.
---@return ToplevelHandle
function toplevel(id) end

---@class SessionProcessHandle
---A program declared with `session_process`. Each field is a signal over its `mantle.processes`
---entry, `nil` before the first push; while `running` is false they describe the finished run.
---@field running Signal<boolean?> Whether it is up.
---@field pid Signal<integer?> Also its process group id. Kept after exit; `nil` before a spawn or after a failed `start`.
---@field started_at Signal<integer?> Unix seconds the current or last run began; `nil` before a spawn or after a failed `start`.
---@field exit_code Signal<integer?> The last finished run's exit status; `nil` while running, before the first run, or after a signal ended it.
---@field start_error Signal<string?> Why the last `start` spawned nothing, usually a command not on `PATH`; `""` when it spawned.
local SessionProcessHandle = {}

---Starts the program unless it is already running, with stdio inherited. The outcome arrives as
---state: `running`, or `start_error`.
---@param cmd string Looked up on `PATH`; no shell, so no globbing, pipes or quoting.
---@param args? string[] Already split: `"a b"` is one argument.
function SessionProcessHandle:start(cmd, args) end

---Sends `signal` to the program itself, not its group. A no-op when it is not running.
---@param signal SignalName
function SessionProcessHandle:signal(signal) end

---Sends the declared `stop_signal` to the program's group, then `SIGKILL` 5 s later. Shell
---shutdown does this to every session process.
function SessionProcessHandle:stop() end

---Declares a program that lives for the session: the Supervisor holds it across reloads and stops
---it at shutdown. Re-declaring a name returns the same handle and re-reads only `stop_signal`, so
---declare at a module's top level. Use `process.run` when you need its output.
---[docs](https://anasgets111.github.io/mantle/guide/processes.html#session_process)
---@param spec { name: string, stop_signal?: SignalName, [string]: "no such property" } `name` keys it in `mantle.processes`; empty raises. `stop_signal` defaults to `"TERM"`.
---@return SessionProcessHandle
function session_process(spec) end

---@class TimerHandle
local TimerHandle = {}

---Disarms the timer, an interval from inside its own callback too. A no-op once a one-shot fired or after a cancel.
function TimerHandle:cancel() end

---Runs `callback` once, `ms` from now, on a monotonic clock, under the Lua CPU budget (ADR-0203).
---Repeat with `interval`. Every evaluation clears all timers, so arm at the top level;
---a discarded handle still fires.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#timer)
---@param ms number `[1, 86400000]`; outside raises.
---@param callback fun() A raise is logged as a warning.
---@return TimerHandle
function timer(ms, callback) end

---Runs `callback` every `ms` until cancelled, like `timer` otherwise. A late turn does not
---queue the missed runs: the next one is `ms` after the late one.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#interval)
---@param ms number `[1, 86400000]`; outside raises.
---@param callback fun() A raise is logged as a warning and the interval keeps running.
---@return TimerHandle
function interval(ms, callback) end

process = {}

---@class ProcessHandle
local ProcessHandle = {}

---`SIGTERM` to its process group, `SIGKILL` 100 ms later; `on_exit` still fires. A no-op after exit.
function ProcessHandle:kill() end

---Spawns `cmd` with stdout and stderr piped and stdin on `/dev/null`, without blocking (ADR-0026).
---The process belongs to the evaluation: a reload kills its group and calls `on_exit(nil)`.
---Callbacks run unbudgeted; a raise is logged as a warning.
---[docs](https://anasgets111.github.io/mantle/guide/processes.html#processrun)
---@param cmd string Looked up on `PATH`; no shell, so no globbing, pipes or quoting.
---@param args? string[] Already split: `"a b"` is one argument. `nil` is none.
---@param on_line fun(line: string, stream: "stdout"|"stderr") Once per line, newline stripped, cut at 64 KiB. Accumulate here and decode in `on_exit`.
---@param on_exit fun(code: integer?) `nil` when a signal ended it or it failed to spawn.
---@return ProcessHandle
function process.run(cmd, args, on_line, on_exit) end

---Spawns `cmd` in its own session with stdio on `/dev/null`; it outlives every reload and the
---shell. No handle, output or exit code, and a spawn failure is only logged (ADR-0188).
---[docs](https://anasgets111.github.io/mantle/guide/processes.html#processdetach)
---@param cmd string Looked up on `PATH`; no shell, so no globbing, pipes or quoting.
---@param args? string[] Already split: `"a b"` is one argument. `nil` is none.
function process.detach(cmd, args) end

palette = {}

---@class PaletteSwatch
---@field color Color `#RRGGBB`.
---@field share number Fraction of the counted (non-transparent) pixels, 0 to 1.

---@class PaletteHandle
local PaletteHandle = {}

---Drops the callback. The decode still finishes.
function PaletteHandle:cancel() end

---Extracts an image's dominant colours off the Lua thread (ADR-0249). `on_done` gets them most common
---first, or `nil` on failure (logged). `on_done` runs unbudgeted.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#palettequantize)
---@param path string A local raster file; no SVG or URL.
---@param opts? { depth?: integer, method?: "celebi"|"wu", rescale?: integer, [string]: "no such property" } `depth` 0 to 8, default 3: up to `2^depth` colours. `method` `"celebi"` (default) or `"wu"`. `rescale` caps the longest edge before counting, default 128, `0` for full size. Out of range raises.
---@param on_done fun(swatches: PaletteSwatch[]?)
---@return PaletteHandle
function palette.quantize(path, opts, on_done) end

---Material 3 colour roles.
---@class PaletteScheme
---@field primary Color
---@field on_primary Color
---@field primary_container Color
---@field on_primary_container Color
---@field inverse_primary Color
---@field primary_fixed Color
---@field primary_fixed_dim Color
---@field on_primary_fixed Color
---@field on_primary_fixed_variant Color
---@field secondary Color
---@field on_secondary Color
---@field secondary_container Color
---@field on_secondary_container Color
---@field secondary_fixed Color
---@field secondary_fixed_dim Color
---@field on_secondary_fixed Color
---@field on_secondary_fixed_variant Color
---@field tertiary Color
---@field on_tertiary Color
---@field tertiary_container Color
---@field on_tertiary_container Color
---@field tertiary_fixed Color
---@field tertiary_fixed_dim Color
---@field on_tertiary_fixed Color
---@field on_tertiary_fixed_variant Color
---@field error Color
---@field on_error Color
---@field error_container Color
---@field on_error_container Color
---@field surface_dim Color
---@field surface Color
---@field surface_tint Color
---@field surface_bright Color
---@field surface_container_lowest Color
---@field surface_container_low Color
---@field surface_container Color
---@field surface_container_high Color
---@field surface_container_highest Color
---@field on_surface Color
---@field on_surface_variant Color
---@field outline Color
---@field outline_variant Color
---@field inverse_surface Color
---@field inverse_on_surface Color
---@field surface_variant Color
---@field background Color
---@field on_background Color
---@field shadow Color
---@field scrim Color

---Material 3 colour roles from one seed colour, as Material Color Utilities builds them.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#palettescheme)
---@param seed Color `#RRGGBB`.
---@param opts? { dark?: boolean, variant?: "tonal_spot"|"vibrant"|"expressive"|"fidelity"|"content"|"neutral"|"monochrome"|"rainbow"|"fruit_salad", contrast?: number, [string]: "no such property" } `dark` default `false`; `variant` default `"tonal_spot"`; `contrast` -1 to 1, default 0. Anything else raises.
---@return PaletteScheme
function palette.scheme(seed, opts) end

---A colour in HCT, Material's colour space.
---@class PaletteHct
---@field hue number Hue in degrees, 0 to under 360.
---@field chroma number Colourfulness from 0; tonal spot's primary palette uses 36.
---@field tone number Lightness, 0 to 100.

---A colour's hue, chroma and tone in HCT, the space Score and schemes work in.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#palettehct)
---@param color Color `#RRGGBB`.
---@return PaletteHct
function palette.hct(color) end

---Up to 4 seed colours ranked by Material 3's Score: chromatic, common and far apart in hue.
---Each is one input swatch's colour as uppercase `#RRGGBB`; `#4285F4` when none qualifies.
---[docs](https://anasgets111.github.io/mantle/guide/scripting.html#palettescore)
---@param swatches PaletteSwatch[] `palette.quantize`'s swatches; only the ratios of their `share`s count.
---@return Color[]
function palette.score(swatches) end
