---@meta
-- GENERATED by `supervisor/src/stubs.rs` for mantle 0.1.0. Do not edit: run `just stubs` and
-- commit what changes.
--
-- Descriptions are the Rust doc comments on the supervisor's `Serialize` payload and action types:
-- document a field there and regenerate. `mantle init` rewrites installed stubs that differ.
--
-- Every capability reads `nil` until its first push. A JSON `null` arrives as an absent key
-- (ADR-0057), so `if item.app_icon then` guards an optional field.

---@class ReadOnlyCapability<T>: Signal<T>
---`:get()` and `:map()` read the pushed payload; `:set()` is refused. `:on_change(handler)` runs once
---per push with the new and previous payload (`nil` on the first), under the 5ms `map` budget, and
---may `invoke` or write state (ADR-0115).
---@field on_change fun(self: ReadOnlyCapability<T>, handler: fun(current: T, previous: T?))

---@class Capability<T>: ReadOnlyCapability<T>

--- Payload types ------------------------------------------------------------------------------

---@class AccessPointInfo
---One scanned network in `available_networks`.
---@field active boolean The Wi-Fi device is associated with this SSID.
---@field band string `"2.4 GHz"`, `"5 GHz"`, `"6 GHz"`, or empty for a frequency outside those bands.
---@field saved boolean A saved NetworkManager profile names this SSID, so `connect` asks for no password.
---@field secure boolean Needs a key: WEP, WPA or RSN.
---@field ssid string Network name; one entry per SSID, from its strongest access point.
---@field strength integer Signal strength, `0` to `100`.

---@class ActiveClient
---The focused window.
---@field class string Wayland `app_id`, e.g. `"firefox"`; the key of `applications.by_app_id`. Empty when unset.
---@field is_floating boolean Whether the window floats rather than tiles.
---@field is_fullscreen? boolean Whether the window is fullscreen (maximized is `false`); `nil` on niri, which does not report it (ADR-0056).
---@field title string Window title; empty when unset.

---@class AppStream
---One app's playback or recording stream (ADR-0053). Streams without a pid are left out.
---@field binary? string `application.process.binary`, e.g. `"firefox"`.
---@field icon? string XDG icon name from `application.icon-name`, else `media.icon-name`, e.g. `"firefox"`.
---@field id integer PipeWire node id, the first argument of `set_app_volume` and `set_app_muted`.
---@field muted boolean Stream mute; `false` until `volume` is known.
---@field name? string `application.name`, if the client set one.
---@field pid integer Owning process id, from `application.process.id`.
---@field process_name? string `/proc/<pid>/comm`, or `nil` if it was unreadable when the stream's properties were read.
---@field recording boolean A capture stream, such as a call's microphone, rather than playback.
---@field volume? number Stream volume, `1.0` is 100%; `nil` until PipeWire reports the stream's `Props`.

---@class AppSummary
---One visible `Type=Application` desktop entry; display data only, argv stays private (ADR-0061).
---@field comment? string `Comment=`, unlocalized, e.g. `"Web Browser"` (ADR-0112); `nil` without the key.
---@field generic_name? string `GenericName=`, unlocalized, e.g. `"Text Editor"`; `nil` without the key.
---@field icon? string `Icon=` as written, a theme name or absolute path, both accepted by `icon { name }`; `nil` without the key.
---@field id string Desktop file id, e.g. `"org.telegram.desktop"`; the argument of `"launch"`.
---@field keywords string[] `Keywords=` split on `;`, for search; empty without the key.
---@field name string `Name=`, unlocalized: `Name[xx]` is not read (ADR-0061).

---@class AudioDevice
---One `sinks` or `sources` entry.
---@field active boolean This is the default output or input; with no default known, the lowest `id` is.
---@field bus? string `device.bus`, e.g. `"pci"`, `"usb"`, `"bluetooth"`.
---@field form_factor? string `device.form-factor`, e.g. `"headset"`.
---@field icon? string `device.icon-name` theme name, e.g. `"audio-card-analog"`.
---@field id integer PipeWire node id, the argument of `set_default_sink`/`set_default_source`; not reboot-stable.
---@field name string `node.description`, e.g. `"Built-in Audio Analog Stereo"`, else `node.nick`, else `node.name`.
---@field port? string The active card route's `port.type`, e.g. `"headphones"`, `"hdmi"`, `"mic"`.

---@alias BatteryStatus
---| "Unknown" # No answer: UPower unreachable, an unknown state number, or a display device that is not a battery.
---| "Charging" # Taking current from an adapter.
---| "Discharging" # Draining.
---| "Empty" # Flat.
---| "FullyCharged" # Charged and holding.
---| "PendingCharge" # On mains, neither draining nor taking current: a charge limit, weak charger or thermal pause.
---| "PendingDischarge" # Waiting to discharge.
---`battery.state`: UPower's `Device.State` by name, e.g. `b.state == "PendingCharge"`.

---@class BluetoothCodecs
---One BlueZ audio device's codec choices, joined to `mantle.bluetooth` by MAC.
---@field active? integer `index` of the active profile; `nil` before PipeWire reports it or when it is not in `codecs`.
---@field codecs CodecProfile[] Available profiles that name a codec, ordered by `index`.
---@field device integer PipeWire device id, the first argument of `set_bluetooth_profile`.
---@field mac string MAC address from the `bluez_card.*` name, `_` turned to `:`.

---@class CodecProfile
---One entry of `BluetoothCodecs::codecs`.
---@field codec string Codec from the profile name, else its English description, e.g. `"AAC"`, `"LDAC"`, `"mSBC"`.
---@field description string PipeWire's description, e.g. `"High Fidelity Playback (A2DP Sink, codec AAC)"`.
---@field index integer Profile index, the second argument of `set_bluetooth_profile`.

---@class ConnectedDevice
---@field battery integer Battery percentage, or `-1` when the device reports none.
---@field busy? DeviceAction Same as `DiscoveredDevice::busy`.
---@field category string From the class of device: `"keyboard"`, `"mouse"`, `"headphones"`, `"headset"`, `"phone"`, `"computer"` or `"generic"`.
---@field mac string MAC address, e.g. `"00:1A:7D:DA:71:11"`; every `bluetooth` action takes it.
---@field name string The device's advertised name, or empty.

---@alias DeviceAction "pairing"|"connecting"|"disconnecting"
---What the shell is doing to a device, as its `busy`.

---@class DiscoveredDevice
---@field blocked boolean BlueZ refuses to pair with or connect to the device until it is unblocked.
---@field busy? DeviceAction The action this shell is running on the device, or `nil`; another client's never shows.
---@field mac string MAC address, the argument of `pair`.
---@field name string Advertised name, often empty when the device broadcasts only an address.
---@field paired boolean Always `false`.

---@class FileEntry
---@field modified integer Modification time in Unix seconds; `0` when unavailable.
---@field name string File name, e.g. `"sunrise.jpg"`.
---@field path string Absolute path.

---@class Folder
---@field entries FileEntry[] Files (and symlinks to files) directly inside, minus dotfiles, filtered by extension and sorted case-insensitively by name. Relisted 200 ms after the last change.
---@field error? string Why listing failed, e.g. `"No such file or directory (os error 2)"`; `nil` on success. A missing or deleted folder is not watched for reappearing.
---@field ready boolean `false` until the first listing lands, then `true` even when empty or failed.

---@class IdleInhibitor
---One holder blocking idle.
---@field who string Free-text holder name, e.g. `"mpv"`; draw it, never match it.
---@field why string Free-text reason, e.g. `"Playing video"`; often empty.

---@class JoinError
---A failed join, as `connect_error`.
---@field message string Display text, such as `"wrong password"` or `"network not found"`.
---@field ssid string The network the join was for.

---@class MenuItem
---One `tray.items[].menu` entry.
---@field children MenuItem[] Submenu entries, empty for a leaf. An app that fills submenus lazily sends them only after `menu_will_show`.
---@field enabled boolean `false` for a greyed-out entry; draw it, but clicking does nothing.
---@field icon_name? string Theme icon name, or `nil`. Icon pixmaps are not carried.
---@field id integer DBusMenu id, the second argument of `activate_menu_item` and `menu_will_show`.
---@field label? string Entry text as sent, or `nil`. `_` mnemonic markers remain (`"_Quit"`); strip them to draw.
---@field menu_type string `"standard"` (the default) or `"separator"`, as the application sent it.
---@field toggle_state? integer `0` off, `1` on, `-1` indeterminate or unreported; `nil` exactly when `toggle_type` is.
---@field toggle_type? string `"checkmark"`, `"radio"`, or `nil` for an entry that is not a toggle.

---@class Notification
---One `notifications.feed` entry (ADR-0033).
---@field actions NotificationAction[] Buttons in sender order, at most 8, excluding `default` and `inline-reply`.
---@field app_icon? string Application icon for `icon { name = ... }`: a theme name such as `"firefox"` or an absolute path, or `nil` (ADR-0091).
---@field app_name string Sending application, truncated to 64 bytes.
---@field body NotificationSpan[] Parsed body markup; the raw body is truncated to 512 bytes first.
---@field desktop_entry? string Sender's desktop id, e.g. `"org.telegram.desktop"`, for `mantle.applications.by_app_id`; `nil` when absent or containing `/` (ADR-0101).
---@field expired boolean The timeout ran out: drop it from popups, keep it in history until dismissed (ADR-0100). Never true for critical or `expire_timeout = 0`; a replacement resets it.
---@field has_default_action boolean Clicking the card may `:invoke("invoke_action", id, "default")`.
---@field has_reply boolean The sender accepts `:invoke("reply", id, text)`.
---@field id integer Server id, from `1`; a replacement keeps the id it replaces.
---@field image_path? string Attached picture (album art, avatar) as an existing absolute path, or `nil`. Never a theme name (ADR-0091).
---@field reply_placeholder? string Placeholder for an empty reply field, e.g. `"Reply to Alice"`, capped at 64 bytes; `nil` when unset (ADR-0101).
---@field summary string Title as sent, truncated to 128 bytes. Not markup-parsed: the spec makes it plain text.
---@field timestamp integer Arrival time, Unix seconds; age is `mantle.system.time - timestamp`. A replacement restamps it.
---@field transient boolean Popup-only: removed on expiry instead of retired to history (ADR-0100).
---@field urgency Urgency `"normal"` when the sender set none. `"critical"` never expires and plays sound through DND.

---@class NotificationAction
---One action button (ADR-0090).
---@field icon_name? string Theme icon name (the key) when the sender set `action-icons`, else `nil`. Never a path.
---@field key string Opaque key for `:invoke("invoke_action", id, key)`.
---@field label string Button label, capped at 64 bytes. An empty label falls back to the key unless `icon_name` is set.

---@class NotificationSpan
---One body-markup run (ADR-0033): styled text or an image.
---@field bold? boolean Whether the run was inside `<b>`.
---@field href? string `<a href>` target, or `nil` when not a link.
---@field image_path? string Existing absolute path under an icon root; images elsewhere are dropped.
---@field italic? boolean Whether the run was inside `<i>`.
---@field kind "text"|"image" Which variant this is; each other field belongs to one variant.
---@field text? string Unescaped text; empty runs are omitted.
---@field underline? boolean Whether the run was inside `<u>`.

---@class OutputWorkspaces
---One output's workspaces.
---@field active_workspace integer `WorkspaceEntry::id` shown on this output.
---@field focused_workspace? integer `WorkspaceEntry::id` with focus, present only on the focused output (ADR-0056).
---@field name string Connector name, e.g. `"eDP-1"`, as in `mantle.screens` and a surface's `monitor`.
---@field workspaces WorkspaceEntry[] Workspaces on this output, sorted by `WorkspaceEntry::idx`.

---@class PairedDevice
---@field blocked boolean BlueZ refuses every connection to or from the device until it is unblocked.
---@field busy? DeviceAction Same as `DiscoveredDevice::busy`.
---@field category string Same set as `ConnectedDevice.category`.
---@field mac string MAC address, the argument of `connect` and `forget`.
---@field name string The device's advertised name, or empty.

---@alias PairingKind "confirm"|"authorize"|"service"|"display"
---What a `pairing_request` asks; see `PairingRequest.kind`.

---@class PairingRequest
---What the pairing agent is asking the user.
---@field code? string Six-digit passkey for `"confirm"`, passkey or PIN for `"display"`, else `nil`.
---@field kind PairingKind `"confirm"`: does the device show `code`? `"authorize"`: may it pair? `"service"`: may a paired, untrusted device connect? `"display"`: type `code` on the device; nothing to answer.
---@field mac string The device's MAC address.
---@field name string The device's advertised name, or empty.

---@alias PlayerCommand "play"|"pause"|"play_pause"|"next"|"previous"

---@class PlayerState
---@field album_art_path string Cover art as an existing absolute path, or empty; a remote `artUrl` is not fetched.
---@field artist string Artists joined with `", "`; empty when unset.
---@field desktop_entry string The player's `.desktop` basename, e.g. `"firefox"`, for app matching; empty when unset.
---@field id string Bus-name suffix after `org.mpris.MediaPlayer2.`, e.g. `"spotify"`; every action takes it.
---@field identity string Display name, e.g. `"Spotify"`; empty if unanswered.
---@field length integer Track length in microseconds, or `-1` when unknown, as for a live stream (ADR-0036).
---@field play_state string `"Playing"`, `"Paused"` or `"Stopped"`; keeps the last value when a read fails, empty if none.
---@field position integer Playback offset in microseconds as of `position_updated_at`, not polled while playing: add elapsed time. `-1` when unknown (ADR-0036).
---@field position_updated_at integer `CLOCK_MONOTONIC` microseconds when `position` was read. No Lua clock shares this epoch (not `mantle.system.monotonic`); only compare it with itself.
---@field title string Track title; empty when unset, normal between tracks.
---@field url string `xesam:url` as sent, e.g. a `file://` path or an `https://` page; empty when unset (ADR-0137).

---@class PrivacyUser
---One app using a camera, microphone or screen capture.
---@field app_name string PipeWire `application.name`, else `/proc/<pid>/comm`, else `"pid 1234"` (or `"node 56"`); never empty.

---@class SessionProcess
---One declared program: its current run, or what is left of its last one.
---@field exit_code? integer Exit status of the last run; `nil` while running, before any run, or when a signal killed it.
---@field pid? integer Process id, also its process group id; kept after exit, `nil` before a spawn or after a failed `start`.
---@field running boolean Whether it is up now. Otherwise the fields below describe the last run.
---@field start_error string Why the last `start` failed to spawn, e.g. a `cmd` not on `PATH`; empty when it spawned.
---@field started_at? integer Unix seconds when the run began; `nil` before a spawn or after a failed `start`.

---@alias SignalName "TERM"|"INT"|"HUP"|"QUIT"|"USR1"|"USR2"|"KILL"|"STOP"|"CONT"
---A signal name without the `SIG` prefix.

---@class SpecialWorkspace
---One Hyprland special workspace (ADR-0119).
---@field app_id? string `app_id` of its representative window, chosen as `WorkspaceEntry::app_id` is.
---@field name string Full name, `"special:scratch"` or `"special"`; the argument of `"toggle_special"`.
---@field populated boolean Whether at least one window sits on it.
---@field shown_on? string Connector showing it, or `nil` while hidden.

---@class SysinfoConfigure
---`sysinfo:configure`'s table. Absent keys keep their interval; one wrong-typed key drops the call.
---@field cpu_interval? integer Seconds between CPU reads; `0` (the default) stops them.
---@field ram_interval? integer Seconds between memory and swap reads; `0` (the default) stops them.
---@field temp_interval? integer Seconds between temperature reads; `0` (the default) stops them.

---@class TrayItem
---@field attention_icon_name? string Artwork to draw while `status == "NeedsAttention"`, paired with `attention_icon_path` like the base icon; both `nil` when unset.
---@field attention_icon_path? string File half of the attention artwork.
---@field icon_name? string Theme icon name for `icon { name = ... }`. At most one of it and `icon_path` is set.
---@field icon_path? string Icon file for `image { source = ... }`: one from the item's `IconThemePath`, or its pixmap spooled to a PNG.
---@field id string Item identity for every `tray` action, e.g. `"1.234/StatusNotifierItem"`. Opaque.
---@field item_is_menu boolean Left click should open `menu` instead of `activate`.
---@field menu? MenuItem[] Top-level menu entries, or `nil` when the item exports no DBusMenu or its first fetch failed.
---@field name string SNI `Title`, or its `Id` when the title is empty.
---@field overlay_icon_name? string Badge to draw over the icon's corner, paired with `overlay_icon_path`; both `nil` when unset.
---@field overlay_icon_path? string File half of the badge.
---@field status string `"Active"`, `"Passive"` (the item asks to be hidden) or `"NeedsAttention"`, as the item sent it.
---@field tooltip? string Tooltip title and text joined by a newline, or `nil` when both are empty.

---@class UpdateCandidate
---One installed package with a newer version.
---@field download_size integer Bytes to fetch; `0` when already cached.
---@field installed_size integer Bytes the new version occupies installed; not a delta.
---@field name string Package name.
---@field new_version string Version on offer.
---@field old_version string Installed version.
---@field repository? string Source repository, e.g. `"extra"` or `"aur"`; empty in a seeded list that lacks it.

---@class UpdatesConfigure
---`configure`'s table. One wrong-typed key drops the whole call (ADR-0034).
---@field aur? boolean Also check the AUR and install through `aur_helper` (ADR-0250). Sends every foreign package name to aur.archlinux.org and builds without PKGBUILD review.
---@field checked_at? integer Persisted Unix seconds of the last successful check. Seeds `last_successful_check` only while that is `nil`, so a restart need not recheck at once.
---@field interval integer Seconds between scheduled checks, the first at once unless `last_successful_check` is younger; `0` checks only on `check`.
---@field packages? UpdateCandidate[] Persisted `packages` from that check, seeded on the same terms; ignored without `checked_at`.

---@alias Urgency "low"|"normal"|"critical"
---Notification urgency, also the `set_sound` tier.

---@class WindowEntry
---One toplevel window. `nil` optional fields are ones the backend does not report.
---@field app_id string Wayland `app_id` (Hyprland's `class`); empty when unset.
---@field floating? boolean Whether the window floats rather than tiles; `nil` on wlr.
---@field focused boolean Whether the window has keyboard focus.
---@field fullscreen? boolean Whether the window is fullscreen; `nil` on niri.
---@field id string Opaque, backend-shaped id for `:invoke`; compare it, never parse it.
---@field maximized? boolean Whether the window is maximized; `nil` on niri.
---@field minimized? boolean Whether the window is minimized; `nil` except on wlr.
---@field output? string Connector name; `nil` when unknown. On wlr, the first output the window entered.
---@field title string Window title; empty when unset.
---@field workspace_id? integer `WorkspaceEntry.id`; `nil` on wlr and on Hyprland special workspaces.

---@class WorkspaceEntry
---One workspace. Draw `idx`, send `id`.
---@field app_id? string `app_id` of a window here (ADR-0117): Hyprland's most recently focused one with an `app_id`; on niri the focused one, else the lowest id, `nil` if that one has no `app_id`. `nil` when empty.
---@field id integer Stable id, the argument of `"focus"`. Hyprland's workspace number; opaque on niri.
---@field idx integer Label number: niri's 1-based position on the output, renumbered on reorder; Hyprland's workspace number, equal to `id` up to `255`, where it saturates.
---@field name? string Workspace name; `nil` when unnamed, or on Hyprland when the name is just the number.
---@field populated boolean Whether a window sits here (ADR-0117).

---@class ApplicationsState
---`mantle.applications` payload (ADR-0061, ADR-0252).
---@field by_app_id table<string, integer> Window `app_id` to its 1-based index: `entries[by_app_id[app_id]]`. Keys are exact `StartupWMClass` and desktop ids, then lowercased and last-dot-segment guesses.
---@field entries AppSummary[] Installed entries, sorted by `name` (byte order). Watched: a change under an applications directory rescans 250 ms after the last event.

---@class AudioState
---`mantle.audio`'s payload (ADR-0053).
---@field apps AppStream[] Apps playing or recording audio, excluding pid-less streams, notification sounds, meters and monitor captures.
---@field balance? number Default output balance, `-1.0` (left) to `1.0` (right); `nil` for mono or an unknown channel map.
---@field bluetooth BluetoothCodecs[] BlueZ audio devices PipeWire knows, with their codecs, ordered by `device`.
---@field muted boolean Default output mute; `false` with no default sink.
---@field sinks AudioDevice[] Every output device.
---@field source_muted boolean Default input (microphone) mute; `false` with no default source.
---@field source_volume? number Default input volume, `1.0` is 100%; `set_source_volume` caps at `1.0`, another client may not. `nil` with no source or before its first volume report.
---@field sources AudioDevice[] Every input device.
---@field volume? number Default output volume, `0.0` to `1.5` (`1.0` is 100%), loudest channel; louder writes by other clients are pulled back to `1.5`. `nil` with no sink or before its first volume report.

---@class BatteryState
---`mantle.battery`'s payload. No battery, or no UPower, reads `present = false` and defaults.
---@field percent integer UPower's `Percentage`, rounded to `0` to `100`; a spurious `0` while not draining keeps the last value.
---@field present boolean UPower's display device is a present battery. Check it before drawing the other fields.
---@field state BatteryStatus What the battery is doing; see `BatteryStatus`.
---@field time_to_empty? integer Seconds until flat, or `nil` while UPower has no estimate.
---@field time_to_full? integer Seconds until full, or `nil` while UPower has no estimate.

---@class IdleState
---`mantle.idle`'s payload (ADR-0141).
---@field inhibited boolean Something holds the session awake: a logind inhibitor (this shell's included), a `ScreenSaver` client (ADR-0231) or a Wayland inhibitor (ADR-0160). No threshold fires while true.
---@field inhibitors IdleInhibitor[] Holders other than this shell, `ScreenSaver` clients included. The compositor's hold has an empty `who`; draw `why` then.

---@class BluetoothState
---@field available boolean BlueZ has an adapter; `false` without one or without `bluetoothd`.
---@field connected_devices ConnectedDevice[] Paired, connected devices. Unordered and may reshuffle on any push: sort before drawing.
---@field discoverable boolean Other devices can find this adapter. BlueZ turns it off after `DiscoverableTimeout` (180 s by default).
---@field discovered_devices DiscoveredDevice[] Unpaired devices BlueZ knows, unordered. Kept after `stop_discovery`; BlueZ expires unseen temporary ones after `TemporaryTimeout` (30 s by default).
---@field discovering boolean The adapter is scanning, whichever client started it.
---@field enabled boolean The adapter is powered.
---@field paired_devices PairedDevice[] Paired devices that are not connected. Unordered like `connected_devices`.
---@field pairing_request? PairingRequest The pairing question to show, or `nil`. Answer with `answer_pairing`.

---@class BrightnessState
---`mantle.brightness`'s payload; the capability stays `nil` on a machine with no backlight.
---@field percent integer Screen backlight, `0` to `100`: the last requested level (sysfs `brightness`), not the mid-fade one.

---@class FilesState
---`mantle.files` payload (ADR-0120).
---@field folders table<string, Folder> One entry per `"watch"`, keyed by its `path` minus trailing slashes; `nil` until watched.

---@class ProcessesState
---`mantle.processes` payload.
---@field sessions table<string, SessionProcess> One entry per `session_process` name; an undeclared name is `nil`.

---@class KeyboardState
---`mantle.keyboard`'s payload (ADR-0034). Lock keys read `false` when no source resolves.
---@field active_layout string Layout display name, e.g. `"English (US)"`; empty before the compositor answers or without one.
---@field active_layout_index integer 0-based position of the active layout, as `switch_layout` takes it.
---@field backlight_pct integer Keyboard backlight, `0` to `100`, or `-1` without a backlight device or readable level. Refreshes on hardware hotkeys and `set_backlight` only, not on other software writes.
---@field caps_lock boolean Caps Lock is on.
---@field layout_count integer Configured layout count; below `2` there is nothing to switch.
---@field num_lock boolean Num Lock is on.
---@field scroll_lock boolean Scroll Lock is on.

---@class LockState
---`mantle.lock`'s payload (ADR-0052).
---@field active boolean The Renderer confirmed the session locked; a requested lock stays `false` until then.
---@field attempts integer Rejected passwords since this lock was confirmed; reset by the next lock.
---@field authenticating boolean A password is with PAM. A second submit is refused while true.
---@field error string Last failure to draw: a rejected password (`"authentication failed"`) or a refused lock's reason. Cleared by a correct password, `lock`, a confirmed lock, and unlock.
---@field unlocking boolean PAM said yes and the lock is still up: the window for an out-animation (ADR-0190).

---@class MprisState
---@field players PlayerState[] Every controllable MPRIS player except `playerctld`, longest-running first, so `players[1]` stays put; empty when none runs.

---@class NetworkState
---`mantle.network`'s payload (ADR-0037).
---@field available_networks AccessPointInfo[] NetworkManager's visible networks, re-read on every change: one per SSID, at most 20, ordered associated, then saved, then strongest. `{}` without Wi-Fi hardware.
---@field connect_error? JoinError The last failed `connect`, or `nil` before any or after a success. Kept until the next `connect`, `cancel_connect` or `abort_connect`; check its `ssid` before showing it.
---@field connected boolean A connection carries the default route; `false` means offline.
---@field connecting_ssid? string The SSID `connect` is joining, or `nil`; clears on a verdict or `abort_connect`.
---@field ethernet_enabled boolean A wired device is activated; `set_ethernet_enabled`'s read-back, unlike carrier.
---@field ethernet_ip? string The first activated wired device's IPv4 address without prefix, or `nil`.
---@field ethernet_present boolean At least one wired device exists, cable or not.
---@field ethernet_speed integer That wired device's link speed in Mb/s; `0` when unknown or none is activated.
---@field networking_enabled boolean NetworkManager networking is on (`NetworkingEnabled`).
---@field password_ssid? string The SSID whose `connect` waits for a password from a `network`/`connect` secure field, or `nil`. Also set after a rejected key; cleared when a join starts or by `cancel_connect`.
---@field scanning boolean A scan is in flight, from the moment `scan` is accepted.
---@field ssid? string `"Ethernet"` when the default route is wired, else the associated SSID, else `nil`. An association still getting an address has an `ssid` while `connected` is `false`.
---@field strength integer The associated network's `strength`, `0` to `100`; `0` without a Wi-Fi association.
---@field wifi_enabled boolean Wi-Fi radio power (`WirelessEnabled`); can be `true` with no Wi-Fi hardware, see `wifi_present`.
---@field wifi_ip? string The Wi-Fi device's IPv4 address without prefix, or `nil`.
---@field wifi_present boolean A Wi-Fi device exists.

---@class NotificationsState
---`mantle.notifications`'s payload (ADR-0033).
---@field dnd boolean Do-not-disturb: mutes non-critical sounds only. Hiding popups is the config's call.
---@field feed Notification[] The newest 20 of up to 100 queued notifications, newest first, expired ones included (ADR-0100); a replacement keeps its place. An entry past 20 stays dismissable by id.

---@class PowerState
---`mantle.power`'s payload. Profile fields are `nil` without power-profiles-daemon, the rest without UPower;
---a failed read is also `nil`. With neither service the capability stays `nil`.
---@field active_profile? string Active platform profile, e.g. `"balanced"`.
---@field energy_rate? number UPower's display-device `EnergyRate` in watts; direction is `mantle.battery.state`.
---@field on_battery? boolean UPower's `OnBattery`: running on battery rather than mains.
---@field profiles? string[] Available profiles in daemon order, e.g. `{"power-saver", "balanced", "performance"}`.

---@class PrivacyState
---@field camera_users PrivacyUser[] One entry per process holding a `/dev/videoN` open; empty when none is. Only devices present when `privacy` started are watched.
---@field microphone_users PrivacyUser[] Apps with a running PipeWire audio capture, one per name (ADR-0137). Idle streams and sink-monitor captures are absent; a muted microphone still counts.
---@field screencast_users PrivacyUser[] Apps with a running PipeWire screen-capture stream, one per name (ADR-0137). wlr-screencopy tools such as `wf-recorder` and `grim` never appear.

---@class SysinfoState
---`mantle.sysinfo`'s payload; `nil` until `configure` sets an interval and a reading lands (ADR-0035).
---@field cpu_percent integer CPU utilization across all cores, `0` to `100`, rounded down; `0` until two samples form a delta.
---@field ram_percent integer Physical memory in use (`MemTotal - MemAvailable`), `0` to `100`, rounded down.
---@field swap_percent integer Swap in use, `0` to `100`, rounded down; also `0` without swap.
---@field temp_cores integer[] CPU temperatures in whole Celsius: per core (`coretemp`) or per CCD (`k10temp`), else one package or `acpitz` reading; empty without a sensor. An unreadable sensor is skipped.
---@field temp_gpu integer `amdgpu`, `nouveau` or `nvidia` hwmon temperature in whole Celsius, or `-1` without a readable one.

---@class SystemState
---`mantle.system`'s payload, pushed once a second.
---@field monotonic integer Seconds since `system` was first used; excludes suspend. Take durations from it, since NTP moves `time`.
---@field time integer Unix epoch seconds, as `os.date` takes them.

---@class StorageState
---`mantle.storage` payload (ADR-0136).
---@field files table<string, any> Each declared `persistent_table`'s contents, keyed by its absolute file path; `nil` until declared. Another writer's change to the file replaces it, unsaved writes included.

---@class PolkitState
---`mantle.polkit`'s payload (ADR-0114). Every other field is empty while `active` is false.
---@field action_id string Action being authorized, e.g. `org.freedesktop.systemd1.manage-units`.
---@field active boolean polkitd is waiting for the user to authenticate.
---@field authenticating boolean A password is with PAM. A second submit is refused while true.
---@field error string Drawable reason for the last failure, e.g. `"authentication failed"`. The prompt stays open to retry.
---@field icon_name string Themed icon name, or empty when the caller set none.
---@field message string Translated prompt text, e.g. `"Authentication is required to ..."`.

---@class TrayState
---@field items TrayItem[] Registered items in registration order, oldest first; updates never reorder them.

---@class UpdatesState
---`mantle.updates`'s payload.
---@field aur_error? string Why AUR packages are missing: the last check's AUR query failed, or `aur` is on with no `aur_helper`; `nil` otherwise. `packages` still holds the repos' answer.
---@field aur_helper? string AUR helper found at start, `"paru"` or `"yay"`, or `nil`; used only once `configure` sets `aur` (ADR-0250).
---@field check_error? string Why the last check failed, or `nil` after a success. A check never modifies the system.
---@field checking boolean A check is running.
---@field consecutive_check_failures integer Check failures in a row; a success resets it to `0`.
---@field count integer Always `#packages`.
---@field install_current_package string Package being installed; empty before the first step line.
---@field install_current_step integer 1-based number of the package being installed, from the manager's `(2/5)`; `0` before the first.
---@field install_error? string Why the package manager could not be run or waited on, or `nil`. Its own failures are `install_exit_code`.
---@field install_exit_code? integer Package manager's exit code for the last install (`0` success); `nil` while running, before one, or when a signal killed it.
---@field install_finished_at? integer Unix seconds when the last install's process ended, whatever its status; `nil` while running, before one, or when it failed to spawn.
---@field install_log string[] The last 200 lines of install output, stdout and stderr interleaved, newest last; cleared when an install starts.
---@field install_total_steps integer Packages in the transaction; `0` until the first step line, so draw progress as indeterminate.
---@field installing boolean An install is running; the `install_*` fields describe the latest run.
---@field last_successful_check? integer Unix seconds of the last successful check (or the `checked_at` seed), else `nil`.
---@field package_manager? string Package manager, e.g. `"pacman"`, or `nil` when unsupported. Set from the first push (ADR-0134).
---@field packages UpdateCandidate[] Pending upgrades. A failed check keeps the last good list.
---@field reboot_required boolean `/run/mantle-reboot-required` exists, watched live. Mantle never writes it; anything you set up may, a pacman hook for example, and `/run` empties on reboot.

---@class WorkspacesState
---`mantle.workspaces` payload; `nil` without niri or Hyprland.
---@field active_client? ActiveClient The focused window, or `nil` when none has focus. One per session, not per output.
---@field compositor string `"niri"` or `"hyprland"` (ADR-0119).
---@field outputs OutputWorkspaces[] One entry per output, sorted by connector name.
---@field overview_open? boolean Whether niri's overview is open; `nil` on Hyprland, which has none.
---@field special? SpecialWorkspace[] Hyprland special workspaces, sorted by name (ADR-0119). `nil` on niri; empty means none exist.

---@class WindowsState
---`mantle.windows` payload; `nil` with no niri, Hyprland or wlr-foreign-toplevel backend.
---@field source string `"niri"`, `"hyprland"`, or `"wlr_foreign_toplevel"`.
---@field windows WindowEntry[] Sorted by `workspace_id`, then backend order; windows without one last.

--- Capabilities -------------------------------------------------------------------------------

---[docs](https://anasgets111.github.io/mantle/capabilities/applications.html)
---@class ApplicationsCapability: Capability<ApplicationsState>
---@field invoke fun(self: ApplicationsCapability, command: "refresh") Rescans installed desktop entries. The directories are watched, so only a failed watch (logged) needs this.
---@field invoke fun(self: ApplicationsCapability, command: "launch", id: string) Launches `entries[].id`, detached; `Terminal=true` entries run in `$TERMINAL`.
---@field invoke fun(self: ApplicationsCapability, command: "open_url", url: string) Opens an `http`, `https` or `mailto` URL (at most 2048 bytes) with `xdg-open` (ADR-0103).

---[docs](https://anasgets111.github.io/mantle/capabilities/audio.html)
---@class AudioCapability: Capability<AudioState>
---@field invoke fun(self: AudioCapability, command: "set_volume", volume: number) Sets master output volume, clamped to `[0.0, 1.5]`.
---@field invoke fun(self: AudioCapability, command: "set_muted", muted: boolean) Sets master output mute.
---@field invoke fun(self: AudioCapability, command: "toggle_mute") Toggles master output mute.
---@field invoke fun(self: AudioCapability, command: "set_balance", balance: number) Sets default output balance, `-1.0` (left) to `1.0` (right), clamped; the louder side keeps its level.
---@field invoke fun(self: AudioCapability, command: "set_default_sink", id: integer) Makes this `sinks[].id` the default output.
---@field invoke fun(self: AudioCapability, command: "set_default_source", id: integer) Makes this `sources[].id` the default input.
---@field invoke fun(self: AudioCapability, command: "set_source_volume", volume: number) Sets default input volume, clamped to `[0.0, 1.0]`.
---@field invoke fun(self: AudioCapability, command: "set_source_muted", muted: boolean) Sets default input mute.
---@field invoke fun(self: AudioCapability, command: "toggle_source_mute") Toggles default input mute.
---@field invoke fun(self: AudioCapability, command: "set_app_volume", id: integer, volume: number) Sets an `apps[].id` stream's volume, clamped to `[0.0, 1.0]`.
---@field invoke fun(self: AudioCapability, command: "set_app_muted", id: integer, muted: boolean) Sets an `apps[].id` stream's mute.
---@field invoke fun(self: AudioCapability, command: "set_bluetooth_profile", device: integer, index: integer) Switches a `bluetooth[].device` to one of its `codecs[].index`.

---[docs](https://anasgets111.github.io/mantle/capabilities/battery.html)
---@class BatteryCapability: ReadOnlyCapability<BatteryState>
local BatteryCapability = {}

---[docs](https://anasgets111.github.io/mantle/capabilities/idle.html)
---@class IdleCapability: ReadOnlyCapability<IdleState>
---@field register_threshold fun(self: IdleCapability, seconds: integer, on_idle: fun(), on_resume: fun()): integer Runs `on_idle` after `seconds` without input and `on_resume` when input returns; returns a handle for `cancel_threshold`. When an earlier registration at the same `seconds` has already gone idle this evaluation, `on_idle` runs at once. Reloads drop registrations.
---@field cancel_threshold fun(self: IdleCapability, handle: integer) Drops one registration; an unknown handle is a no-op.
---@field inhibit fun(self: IdleCapability, reason: string) Holds off idle system-wide (a logind `idle` inhibitor) until `release_inhibit`. Counted; holds survive in-place reloads and drop when the Renderer restarts.
---@field release_inhibit fun(self: IdleCapability) Releases one `inhibit` hold; with none held, a no-op.
local IdleCapability = {}

---[docs](https://anasgets111.github.io/mantle/capabilities/bluetooth.html)
---@class BluetoothCapability: Capability<BluetoothState>
---@field invoke fun(self: BluetoothCapability, command: "set_enabled", enabled: boolean) Powers the adapter on or off.
---@field invoke fun(self: BluetoothCapability, command: "set_discoverable", discoverable: boolean) Makes the adapter findable by other devices, or not.
---@field invoke fun(self: BluetoothCapability, command: "start_discovery") Clears `discovered_devices` and scans. The request holds, so a scan starts once the adapter powers on and pauses while a `pair` runs.
---@field invoke fun(self: BluetoothCapability, command: "stop_discovery") Stops discovery; `discovered_devices` stays.
---@field invoke fun(self: BluetoothCapability, command: "pair", mac: string) Pairs a discovered device, then trusts and connects it.
---@field invoke fun(self: BluetoothCapability, command: "connect", mac: string) Trusts and connects a paired device.
---@field invoke fun(self: BluetoothCapability, command: "disconnect", mac: string) Disconnects a connected device.
---@field invoke fun(self: BluetoothCapability, command: "forget", mac: string) Removes a device from BlueZ, unpairing it.
---@field invoke fun(self: BluetoothCapability, command: "answer_pairing", mac: string, accept: boolean) Accepts or rejects the `pairing_request` for `mac`; a yes within 750 ms of it appearing is ignored.

---[docs](https://anasgets111.github.io/mantle/capabilities/brightness.html)
---@class BrightnessCapability: Capability<BrightnessState>
---@field invoke fun(self: BrightnessCapability, command: "set", percent: integer) Sets the screen backlight, `0` to `100`; higher clamps to `100`.

---[docs](https://anasgets111.github.io/mantle/capabilities/files.html)
---@class FilesCapability: Capability<FilesState>
---@field invoke fun(self: FilesCapability, command: "watch", path: string, extensions?: string[]) Keeps `folders[path]` listing an absolute folder. `extensions` match case-insensitively, dot optional; omitted means every file.
---@field invoke fun(self: FilesCapability, command: "unwatch", path: string) Stops watching `path` and removes it from `folders`.

---[docs](https://anasgets111.github.io/mantle/capabilities/processes.html)
---@class ProcessesCapability: Capability<ProcessesState>
---@field invoke fun(self: ProcessesCapability, command: "declare", name: string, stop_signal?: SignalName) Registers `name` (required before `start`) and sets its stop signal, default `TERM`. Redeclaring updates the signal without touching a running program.
---@field invoke fun(self: ProcessesCapability, command: "start", name: string, cmd: string, args?: string[]) Runs `cmd` with `args` (no shell) as its own process group. No-op while `running` or when `name` is undeclared.
---@field invoke fun(self: ProcessesCapability, command: "signal", name: string, signal: SignalName) Sends `signal` to the program's process (not its group); no-op when not running.
---@field invoke fun(self: ProcessesCapability, command: "stop", name: string) Sends the declared stop signal to the process group, then `KILL` if it is still up 5 s later; no-op when not running.

---[docs](https://anasgets111.github.io/mantle/capabilities/keyboard.html)
---@class KeyboardCapability: Capability<KeyboardState>
---@field invoke fun(self: KeyboardCapability, command: "set_backlight", percent: integer) Sets the keyboard backlight, `0` to `100`; higher clamps to `100`.
---@field invoke fun(self: KeyboardCapability, command: "switch_layout", index: integer) Switches to the 0-based configured layout `index`.

---[docs](https://anasgets111.github.io/mantle/capabilities/lock.html)
---@class LockCapability: Capability<LockState>
---`mantle.lock` actions. There is no `unlock`; only a correct password unlocks (ADR-0042).
---@field invoke fun(self: LockCapability, command: "lock") Locks the session; a no-op while `active`.
---@field invoke fun(self: LockCapability, command: "set_unlock_animation", ms?: integer) Keeps the lock up `ms` after a correct password for an out-animation (ADR-0190). Clamped to 600; omitted is `0`.

---[docs](https://anasgets111.github.io/mantle/capabilities/mpris.html)
---@class MprisCapability: Capability<MprisState>
---@field invoke fun(self: MprisCapability, command: "control", id: string, cmd: PlayerCommand) Sends a playback command to `players[].id`.
---@field invoke fun(self: MprisCapability, command: "seek", id: string, position_us: integer) Seeks to an absolute position in microseconds, clamped to `[0, length]` (only `>= 0` when `length` is `-1`).
---@field invoke fun(self: MprisCapability, command: "seek_relative", id: string, offset_us: integer) Seeks by a signed offset in microseconds, unclamped; past the end may skip to the next track.

---[docs](https://anasgets111.github.io/mantle/capabilities/network.html)
---@class NetworkCapability: Capability<NetworkState>
---@field invoke fun(self: NetworkCapability, command: "set_networking_enabled", enabled: boolean) Turns NetworkManager networking on or off.
---@field invoke fun(self: NetworkCapability, command: "set_wifi_enabled", enabled: boolean) Powers the Wi-Fi radio.
---@field invoke fun(self: NetworkCapability, command: "set_ethernet_enabled", enabled: boolean) `false` disconnects every wired device; `true` activates each one's autoconnect profile, and a device without one stays down.
---@field invoke fun(self: NetworkCapability, command: "scan") Requests a Wi-Fi scan; a no-op without Wi-Fi hardware.
---@field invoke fun(self: NetworkCapability, command: "connect", ssid: string, hidden: boolean) Joins a network. Without a saved profile, a secured, `hidden` or out-of-range one sets `password_ssid` and waits for a key.
---@field invoke fun(self: NetworkCapability, command: "cancel_connect") Drops the password request `password_ssid` names; a join already running continues.
---@field invoke fun(self: NetworkCapability, command: "abort_connect") Stops the join `connecting_ssid` names, deleting a profile the join created.
---@field invoke fun(self: NetworkCapability, command: "forget", ssid: string) Deletes every saved profile for this SSID.
---@field invoke fun(self: NetworkCapability, command: "disconnect_wifi") Disconnects Wi-Fi; NetworkManager does not autoconnect it again until the next join.

---[docs](https://anasgets111.github.io/mantle/capabilities/notifications.html)
---@class NotificationsCapability: Capability<NotificationsState>
---@field invoke fun(self: NotificationsCapability, command: "dismiss", id: integer) Removes a queued notification.
---@field invoke fun(self: NotificationsCapability, command: "invoke_action", id: integer, key: string) Invokes an `actions[].key`, or `"default"`; removes the notification unless it is resident.
---@field invoke fun(self: NotificationsCapability, command: "reply", id: integer, text: string) Sends reply text to a notification with `has_reply`; removes it unless it is resident.
---@field invoke fun(self: NotificationsCapability, command: "set_sound", urgency: Urgency, path: string) Sets an urgency tier's sound: an existing file under `/usr/share`, `/usr/local/share`, `/opt` or `$XDG_DATA_HOME`, else ignored. Only Ogg Vorbis and 16-bit PCM WAV play.
---@field invoke fun(self: NotificationsCapability, command: "set_dnd", enabled: boolean) Gates non-critical notification sounds.
---@field invoke fun(self: NotificationsCapability, command: "set_quiet", enabled: boolean) Mutes non-critical sounds like `set_dnd`, without changing `dnd`.
---@field invoke fun(self: NotificationsCapability, command: "set_app_muted", app: string, muted: boolean) Silences every sound from an app, critical included, matched exactly on `app_name` or `desktop_entry`.
---@field invoke fun(self: NotificationsCapability, command: "hold_expiry", seconds: integer) Pauses every expiry countdown for `seconds`, capped at 300; `0` releases the hold.

---[docs](https://anasgets111.github.io/mantle/capabilities/power.html)
---@class PowerCapability: Capability<PowerState>
---@field invoke fun(self: PowerCapability, command: "set_profile", name: string) Switches to one of `profiles`. Not validated here; a rejected name is logged and `active_profile` stays.

---[docs](https://anasgets111.github.io/mantle/capabilities/privacy.html)
---@class PrivacyCapability: ReadOnlyCapability<PrivacyState>
local PrivacyCapability = {}

---[docs](https://anasgets111.github.io/mantle/capabilities/sysinfo.html)
---@class SysinfoCapability: Capability<SysinfoState>
---@field invoke fun(self: SysinfoCapability, command: "configure", intervals: SysinfoConfigure) Sets poll intervals; every one starts at `0`, so nothing is read until this. The first reading lands one interval later (CPU: two).

---[docs](https://anasgets111.github.io/mantle/capabilities/system.html)
---@class SystemCapability: ReadOnlyCapability<SystemState>
local SystemCapability = {}

---[docs](https://anasgets111.github.io/mantle/capabilities/storage.html)
---@class StorageCapability: Capability<StorageState>
---@field invoke fun(self: StorageCapability, command: "open", path: string, defaults?: table<string, any>) Loads an absolute JSON file into `files[path]`, filling missing top-level keys from `defaults`. `persistent_table` sends this; stored values win over defaults.
---@field invoke fun(self: StorageCapability, command: "set", path: string, key: string, value?: any) Sets `key` in a declared file, `nil` deleting it; saved 1 s after the last write.

---[docs](https://anasgets111.github.io/mantle/capabilities/polkit.html)
---@class PolkitCapability: Capability<PolkitState>
---@field invoke fun(self: PolkitCapability, command: "cancel") Dismisses the prompt; the requesting program sees the request cancelled.

---[docs](https://anasgets111.github.io/mantle/capabilities/tray.html)
---@class TrayCapability: Capability<TrayState>
---@field invoke fun(self: TrayCapability, command: "activate", id: string, x: integer, y: integer) Left-click activation at screen coordinates `x`, `y`; a no-op when `item_is_menu`.
---@field invoke fun(self: TrayCapability, command: "secondary_activate", id: string, x: integer, y: integer) Middle-click activation at screen coordinates `x`, `y` (ADR-0074).
---@field invoke fun(self: TrayCapability, command: "scroll", id: string, delta: integer, orientation: string) Scrolls the icon by `delta`; `orientation` is `"vertical"` or `"horizontal"`, passed verbatim (ADR-0074).
---@field invoke fun(self: TrayCapability, command: "activate_menu_item", id: string, menu_item_id: integer) Clicks the item's `MenuItem.id`.
---@field invoke fun(self: TrayCapability, command: "menu_will_show", id: string, submenu_id: integer) Tells the application submenu `submenu_id` is opening, then refetches the menu unless it answers that nothing changed.

---[docs](https://anasgets111.github.io/mantle/capabilities/updates.html)
---@class UpdatesCapability: Capability<UpdatesState>
---@field invoke fun(self: UpdatesCapability, command: "check") Checks for upgrades now, even when dormant; ignored while `checking`.
---@field invoke fun(self: UpdatesCapability, command: "configure", config: UpdatesConfigure) Sets the check schedule and AUR use, and seeds a remembered check.
---@field invoke fun(self: UpdatesCapability, command: "install") Runs a full upgrade, `pkexec pacman -Syu --noconfirm` or `aur_helper` when `aur` is on; ignored while `installing`.

---[docs](https://anasgets111.github.io/mantle/capabilities/workspaces.html)
---@class WorkspacesCapability: Capability<WorkspacesState>
---@field invoke fun(self: WorkspacesCapability, command: "focus", id: integer) Focuses a `WorkspaceEntry.id`. Hyprland creates a missing number; niri ignores it.
---@field invoke fun(self: WorkspacesCapability, command: "toggle_special", name: string) Shows or hides a `special[].name` on Hyprland, creating an unknown one; no-op on niri.

---[docs](https://anasgets111.github.io/mantle/capabilities/windows.html)
---@class WindowsCapability: Capability<WindowsState>
---@field invoke fun(self: WindowsCapability, command: "focus", id: string) Focuses a window.
---@field invoke fun(self: WindowsCapability, command: "close", id: string) Asks the compositor to close the window.
---@field invoke fun(self: WindowsCapability, command: "set_fullscreen", id: string, fullscreen: boolean) Sets fullscreen on or off; no-op on niri.
---@field invoke fun(self: WindowsCapability, command: "set_minimized", id: string, minimized: boolean) Sets minimized on or off; wlr only.
---@field invoke fun(self: WindowsCapability, command: "set_maximized", id: string, maximized: boolean) Sets maximized on or off; no-op on niri.

--- Off-roster members ---------------------------------------------------------------------------
-- Written by hand in `stubs.rs`: `Screen` and `RescueState` come from the Renderer, not a capability.

---@class Screen
---@field name string Connector name, e.g. `"eDP-1"`, as a surface's `monitor` takes it; `"output-N"` below `wl_output` v4.
---@field x integer Left edge in compositor space: `xdg_output`'s logical position, else `wl_output`'s.
---@field y integer Top edge, on the same terms as `x`.
---@field width integer Logical pixels (already divided by scale); the mode's pixels when no logical size is known.
---@field height integer Logical pixels, on the same terms as `width`.
---@field scale integer Integer scale factor, e.g. `2` on HiDPI. `width` and `height` are already logical.
---@field fractional_scale number Real scale, e.g. `1.5`: mode width over logical width; `scale` without both.
---@field refresh number Refresh rate in Hz; `0` without a current mode, e.g. a virtual output.
---@field orientation Orientation The `wl_output` transform.
---@field model string Monitor model, e.g. `"DELL U2720Q"`; stable across connector renames. Empty when unadvertised.
---@field description? string The compositor's human label; format varies (Hyprland's has the serial). Absent below `wl_output` v4.

---@alias Orientation
---| "normal" # No transform.
---| "90" # Rotated 90 degrees counter-clockwise.
---| "180" # Rotated 180 degrees.
---| "270" # Rotated 270 degrees counter-clockwise.
---| "flipped" # Mirrored around a vertical axis, no rotation.
---| "flipped_90" # Mirrored, then rotated 90 degrees counter-clockwise.
---| "flipped_180" # Mirrored, then rotated 180 degrees.
---| "flipped_270" # Mirrored, then rotated 270 degrees counter-clockwise.

---@class RescueState
---@field is_rescue boolean The last evaluation, apply or live update failed, or the session lock was refused or ended; the previous scene stays up (ADR-0046). The next reload that applies clears it.
---@field error_log string The Lua error, ready to draw; empty while `is_rescue` is false.

---@class MantleVersion
---@field major integer The Renderer's `CARGO_PKG_VERSION_MAJOR`.
---@field minor integer The Renderer's `CARGO_PKG_VERSION_MINOR`.
---@field patch integer The Renderer's `CARGO_PKG_VERSION_PATCH`.

---@class Mantle
---@field audio AudioCapability PipeWire: output and input volume and mute, device lists, per-app streams and Bluetooth codecs.
---@field network NetworkCapability NetworkManager: connectivity, Wi-Fi and wired state, scanned access points and join progress.
---@field bluetooth BluetoothCapability BlueZ: adapter power, discovery, connected, paired and discovered devices, and pairing prompts.
---@field tray TrayCapability StatusNotifierItem: registered tray items with artwork, status and menus.
---@field notifications NotificationsCapability The notification server: the newest 20 notifications and do-not-disturb.
---@field mpris MprisCapability MPRIS: media players with track metadata, playback state and position.
---@field sysinfo SysinfoCapability CPU, memory and swap use, CPU and GPU temperatures. `nil` until `configure` sets intervals.
---@field keyboard KeyboardCapability Lock keys, the active layout and the keyboard backlight.
---@field privacy PrivacyCapability Apps using the camera, microphone or screen capture right now.
---@field updates UpdatesCapability Pending package upgrades (pacman, optionally AUR), install progress and whether a reboot is due.
---@field lock LockCapability The session lock: whether it is held, authentication progress and the last failure.
---@field polkit PolkitCapability The pending polkit authentication request, its progress and the last failure.
---@field battery BatteryCapability UPower's display device: charge, state and time estimates.
---@field system SystemCapability Wall and monotonic clocks, pushed once a second.
---@field brightness BrightnessCapability The screen backlight percentage; `nil` without a backlight.
---@field workspaces WorkspacesCapability Workspaces per output, special workspaces and the focused window.
---@field power PowerCapability Power profiles, mains or battery, and battery power draw.
---@field applications ApplicationsCapability Installed desktop entries, indexed by window `app_id`.
---@field files FilesCapability Live file listings of watched folders.
---@field storage StorageCapability Each `persistent_table` JSON file, keyed by absolute path.
---@field idle IdleCapability Idle inhibitors, plus threshold and inhibit methods.
---@field processes ProcessesCapability Programs declared with `session_process`: running state, start time and last exit.
---@field windows WindowsCapability Open toplevel windows with title, app ID, workspace, output and state flags.
---@field screens ReadOnlyCapability<Screen[]> Connected outputs from the Renderer. `{}` rather than `nil` at first evaluation (ADR-0041). [docs](https://anasgets111.github.io/mantle/capabilities/index.html#renderer-members)
---@field rescue ReadOnlyCapability<RescueState> Whether the last evaluation, apply, live update or the session lock failed; the previous scene stays up (ADR-0046). [docs](https://anasgets111.github.io/mantle/capabilities/index.html#renderer-members)
---@field version MantleVersion The engine's version. Not a signal. [docs](https://anasgets111.github.io/mantle/capabilities/index.html#renderer-members)
---@field config_dir string Directory `shell.lua` was loaded from, for naming files shipped beside it. Not a signal. [docs](https://anasgets111.github.io/mantle/capabilities/index.html#renderer-members)
mantle = {}
