---@meta
-- The eleven node kinds and their properties. Surface roles live in `surfaces.lua`.
--
-- GENERATED by `renderer/src/lua/nodes/stubs.rs` from the property table in
-- `renderer/src/lua/nodes/properties.rs`, which the engine's name check and parsers read. Do not
-- edit: change the table, run `just stubs` and commit what changes.
--
-- `Bound` in a union means the property also takes a signal, read again once it is written. It is
-- `userdata`, not `Signal`, so table payloads are not mistaken for signals. `id` and callbacks take
-- no signal; `hover`, `focused`, `scroll`, `geometry` and `elided` take the handle itself. `[string]: "no such property"`
-- makes a misspelled key a type error.

---A node table, as one of the constructors below returns it. A class, so a `Surface` is not one;
---the index keeps a field set after construction legal.
---@class Node
---@field [string] any
---@alias Align "start"|"center"|"end"|"stretch"
-- ponytail: copied from cursor-icon 1.2's `FromStr`, which exposes no list to derive it from; the
-- stub probe catches a name it refuses, not one missing here. Upgrade: derive once the crate lists them.
---@alias Cursor "default"|"pointer"|"text"|"not-allowed"|"grab"|"grabbing"|"move"|"crosshair"|"wait"|"progress"|"help"|"context-menu"|"cell"|"vertical-text"|"alias"|"copy"|"no-drop"|"zoom-in"|"zoom-out"|"all-scroll"|"col-resize"|"row-resize"|"n-resize"|"e-resize"|"s-resize"|"w-resize"|"ne-resize"|"nw-resize"|"se-resize"|"sw-resize"|"ew-resize"|"ns-resize"|"nesw-resize"|"nwse-resize" CSS cursor name (same as `wp_cursor_shape_v1`).
---@alias Edges { top?: number, right?: number, bottom?: number, left?: number, [string]: "no such property" } Per-edge pixels; a missing edge is `0`.
---@alias Corners { top_left?: number, top_right?: number, bottom_right?: number, bottom_left?: number, [string]: "no such property" } Per-corner radius px; a missing corner is `0`.
-- ponytail: whole percents only, so a fraction (`"12.5%"`) or one above `"100%"`, which the engine
-- accepts, is flagged. Upgrade: a pattern type, which LuaLS lacks.
---@alias Percent "0%"|"1%"|"2%"|"3%"|"4%"|"5%"|"6%"|"7%"|"8%"|"9%"|"10%"|"11%"|"12%"|"13%"|"14%"|"15%"|"16%"|"17%"|"18%"|"19%"|"20%"|"21%"|"22%"|"23%"|"24%"|"25%"|"26%"|"27%"|"28%"|"29%"|"30%"|"31%"|"32%"|"33%"|"34%"|"35%"|"36%"|"37%"|"38%"|"39%"|"40%"|"41%"|"42%"|"43%"|"44%"|"45%"|"46%"|"47%"|"48%"|"49%"|"50%"|"51%"|"52%"|"53%"|"54%"|"55%"|"56%"|"57%"|"58%"|"59%"|"60%"|"61%"|"62%"|"63%"|"64%"|"65%"|"66%"|"67%"|"68%"|"69%"|"70%"|"71%"|"72%"|"73%"|"74%"|"75%"|"76%"|"77%"|"78%"|"79%"|"80%"|"81%"|"82%"|"83%"|"84%"|"85%"|"86%"|"87%"|"88%"|"89%"|"90%"|"91%"|"92%"|"93%"|"94%"|"95%"|"96%"|"97%"|"98%"|"99%"|"100%" `"NN%"` of the parent's box (the output's, on a panel).
---@alias Length number|"fill"|Percent Pixels `[0, 8192]`, the remaining space, or a percent.
---@alias Color string `"#RRGGBB"` or `"#RRGGBBAA"`. No shorthand or names.
---@alias BorderColors { top?: Color, right?: Color, bottom?: Color, left?: Color, [string]: "no such property" } Per-edge colours; a signal inside is refused.
---@alias Axes { x?: number, y?: number, [string]: "no such property" } A missing axis takes the property's default.
---@alias GradientStop [number, Color] Position `[0, 1]` and colour. Positions ascend.
---@alias PathCommand { op: "M"|"L"|"Q"|"C"|"A"|"Z", points: number[], hole?: boolean, [string]: "no such property" } Node-local logical pixels. Q has one control point, C has two, then the endpoint. A is centre x, centre y, radius, start and sweep in degrees clockwise from the +x axis. `hole` on a subpath's first command cuts it out of the fill, whatever its winding.
---@alias Gradient { gradient: "linear"|"radial"|"conic", angle?: number, stops: GradientStop[], [string]: "no such property" } At least 2 stops. `angle` is degrees clockwise from the top: `"linear"` default `180`, `"conic"` default `0`, `"radial"` refuses it.
---@alias Mask { gradient?: "linear"|"radial"|"conic", angle?: number, stops?: GradientStop[], source?: string, node?: string, invert?: boolean, [string]: "no such property" } Exactly one of a `Gradient`, an image `source` path (alpha only, stretched over the box), or `node` naming a direct child id (alpha in its laid-out position). `invert` swaps kept and cut.
---@alias EasingName "linear"|"in_quad"|"out_quad"|"in_out_quad"|"in_cubic"|"out_cubic"|"in_out_cubic"|"in_quart"|"out_quart"|"in_out_quart"|"in_quint"|"out_quint"|"in_out_quint"|"in_sine"|"out_sine"|"in_out_sine"|"in_expo"|"out_expo"|"in_out_expo"|"in_circ"|"out_circ"|"in_out_circ"|"in_back"|"out_back"|"in_out_back"|"in_elastic"|"out_elastic"|"in_out_elastic"|"in_bounce"|"out_bounce"|"in_out_bounce" The `back` and `elastic` families overshoot, as does a Bezier `y` outside `[0, 1]`; the property's range clamps them.
---@alias Easing EasingName|[number, number, number, number]|{ steps: integer, [string]: "no such property" } A name, CSS `cubic-bezier` `{ x1, y1, x2, y2 }` with `x1`, `x2` in `[0, 1]`, or `{ steps = n }`, `n` in `[1, 1000]` (ADR-0151).
---@alias Keyframe number|string|Edges|Corners|Axes|PathCommand[]|{ value: number|string|Edges|Corners|Axes|PathCommand[], duration?: number, easing?: Easing, [string]: "no such property" } A bare value, or a frame with its own timing. `duration = 0` jumps; repeating the previous value holds.
---@alias Spring { stiffness: number, damping: number, [string]: "no such property" } Both required: `stiffness` `(0, 100000]`, `damping` `(0, 10000]`; `2 * math.sqrt(stiffness)` is critical damping. Keeps its velocity when the target changes (ADR-0154).
---@alias Animation number|{ duration?: number, delay?: number, easing?: Easing, from?: number|string|Edges|Corners|Axes|PathCommand[], spring?: Spring, keyframes?: Keyframe[], loops?: integer|"infinite", [string]: "no such property" } A bare number is `duration`.
--- - `duration`: ms `[1, 60000]`, required unless `spring`. `easing` defaults to `"in_out_quad"`.
--- - `delay`: ms `[0, 60000]` before it starts; offsets a sequence once, not per loop (ADR-0153).
--- - `from`: start value when the node did not display the property last pass (a new node, or one that lacked it); otherwise the first value snaps (ADR-0146). Refused beside `keyframes`.
--- - `spring`: replaces `duration`, `easing`, `keyframes` and `loops`, which are refused beside it.
--- - `keyframes`: at least 2 values, no holes, at least one segment with time; walks instead of easing to the resolved value (ADR-0152). `loops` `[1, 10000]` or `"infinite"`, default `1`, only with `keyframes`. Bind `animate` to start or stop one.
---@alias MoveAnimation number|{ duration: number, delay?: number, easing?: Easing, [string]: "no such property" } `animate.move`: eased timing for a matched node's changed layout position. A bare number is `duration`; a table requires `duration`. `from`, `keyframes`, `loops` and `spring` are refused.
---@alias Animations table<string, Animation> Property name to animation, plus `move` and `exit`; each kind's `animate` field names its own, e.g. `RectAnimations`. Names the node does not accept, `z` and `animate` are refused. Numbers, percents, colours and numeric `Edges`/`Corners`/`Axes` tween against the same shape; anything else snaps.
---@alias Exit { duration?: number, delay?: number, easing?: Easing, spring?: Spring, [string]: any } `animate.exit`: timing as in `Animation` (`duration` or `spring` required once a target is named) plus `property = target` pairs the node eases to after a pass drops it (ADR-0150). A target starts from the shown value, or from the identity: `1` for `opacity`/`scale`, `0.5` for `origin`, alpha 0 for a colour, `0` otherwise.

---[docs](https://anasgets111.github.io/mantle/nodes/index.html#common-properties)
---@class NodeBase
---@field width? Length|Bound `[0, 8192]`, default: content.
---@field height? Length|Bound `[0, 8192]`, default: content. As `width`.
---@field max_width? number|Bound `[0, 8192]`. Pixel ceiling, CSS `max-width`. Content past it overflows; `scroll` on the same node scrolls it.
---@field max_height? number|Bound `[0, 8192]`. Pixel ceiling, as `max_width`.
---@field min_width? number|Bound `[0, 8192]`. Pixel floor, CSS `min-width`; wins over a lower `max_width`.
---@field min_height? number|Bound `[0, 8192]`. Pixel floor, as `min_width`.
---@field padding? number|Edges|Bound `[0, 8192]`, default `0`. Inner spacing; a number sets all four edges. Each edge must be within `[0, 8192]`.
---@field visible? boolean|Bound Default `true`. `false` removes the node from layout, paint and spacing but keeps its subtree frozen in memory (ADR-0124); to switch views, bind the parent's `children`.
---@field opacity? number|Bound `[0, 1]`, default `1`. Multiplied down the tree. At `0` the node still takes space and input.
---@field z? number|Bound Default `0`. Sibling paint and hit order. Higher paints later and hits first; ties keep declaration order. Layout and focus ignore it; `animate` refuses it (ADR-0259).
---@field scale? number|Axes|Bound `[0, 64]`, default `1`. About `origin`; a missing axis is `1`. Paint only: layout and `geometry` see the unscaled box; hit-testing follows the painted one (ADR-0149).
---@field rotate? number|Bound `[-8192, 8192]`, default `0`. Degrees clockwise about `origin`. Paint only.
---@field translate? Axes|Bound `[-8192, 8192]`, default `{ x = 0, y = 0 }`. Pixel offset per axis, a missing one `0`, applied after `scale` and `rotate`. Paint only.
---@field origin? Axes|Bound `[0, 1]`, default `{ x = 0.5, y = 0.5 }`. Pivot for `scale` and `rotate` as box fractions; a missing axis is `0.5`.
---@field shadow_color? Color|Bound Default `"#000000"`. Draws when alpha > 0 and `shadow_blur`, `shadow_offset` or `shadow_spread` is set. Clipped at the parent's box: pad the parent or give it `clip = "none"` (ADR-0254).
---@field shadow_blur? number|Bound `[0, 8192]`, default `0`. CSS `box-shadow` blur radius in px (ADR-0262).
---@field shadow_offset? Axes|Bound `[-8192, 8192]`, default `{ x = 0, y = 0 }`. Shadow offset in px per axis. Follows the node's transform.
---@field shadow_spread? number|Bound `[-8192, 8192]`, default `0`. Px the shadow grows per side; negative shrinks it. On non-box content it scales the shadow about the box centre.
---@field content_blur? number|Bound `[0, 8192]`, default `0`. Gaussian sigma in px over this node's painted subtree, CSS `filter: blur()`. Clipped like a shadow (ADR-0254).
---@field id? string Unique among siblings; matches this node across passes. Siblings without one match by position (ADR-0045).
---@field accessible_name? string|Bound Default `""`. Spoken name for a control. A node with `on_click` or `submit` becomes keyboard focusable when this is set. Give each textfield a name for screen readers.
---@field focus_ring? boolean|Bound Default `true`. `false` keeps the engine's focus outline off this node; style it from `focused(name)` instead.
---@field focused? Bound A `focused(name)` signal; true while this node or a node inside it holds keyboard control focus.
---@field hover? Bound A `hover(name)` signal; this node's box is its region.
---@field geometry? Bound A `geometry(name)` signal; layout writes this node's surface-local rect into it (ADR-0147).
---@field cursor? Cursor|Bound Default: `"pointer"` on a node with `on_click`, `on_drag`, `on_wheel` or `submit` and on a link, `"text"` on a `textfield`, else the arrow. Pointer shape over this node; the innermost node that sets one wins (ADR-0107).
---@field on_hover? fun(hovered: boolean) Called on each hover edge from pointer Enter, Motion or Leave; layout changes under a still pointer do not call it. Refused without `hover` on the same node.
---@field on_click? fun(rect: Rect, button: "left"|"right"|"middle", pointer: { x: number, y: number }) On release over the same node that was pressed, with the same mouse button. `rect` is the node's surface-local box, before transforms. `pointer` is node-local and unclamped like `on_drag`'s; Enter, Space and screen-reader activation report the node's centre. A press on a `textfield` that takes the keyboard goes to the field instead.
---@field on_drag? fun(rect: Rect, pointer: { x: number, y: number }, phase: "start"|"move"|"end") Left-button drag (ADR-0116). `pointer` is node-local and unclamped. `"start"` on press, `"end"` on release (before `on_click`) or when the pointer leaves the surface.
---@field on_wheel? fun(rect: Rect, steps: number) Vertical wheel in notches, positive away from the user, fractional on touchpads (ADR-0116). The innermost handler or scroll container wins; on one node, the `scroll`.
---@field submit? boolean|Bound Default `false`. A click also submits the armed `secure_submit` field, like Enter (ADR-0114). Works without `on_click` and runs before it.
---@field hittable? boolean|Bound Default: inherited; `true` at the root. `false` makes this node and every descendant transparent to the pointer: no click, drag, wheel, hover or cursor, and its box claims no input region, so what is underneath gets them. Inherited; a descendant that sets `true` is hit again, and this node's own handlers, cursor and hover then still apply to it.
---@field [string] "no such property"

---Placement in a parent, which a surface root lacks.
---[docs](https://anasgets111.github.io/mantle/nodes/index.html#common-properties)
---@class PlacedBase
---@field margin? number|Edges|Bound Default `0`. Outer spacing; a number sets all four edges. Not range-checked.
---@field align_h? Align|Bound Default `"start"`. Places the node in its parent: both axes under a stacking parent, only the cross axis under a `row`/`column`/`list`. On a `row` it also packs the children, which ignore their own (`"stretch"` packs as `"start"`). `"stretch"` overrides a pixel size; `"fill"` off the parent's flow axis overrides alignment.
---@field align_v? Align|Bound Default `"start"`. As `align_h` with the axes swapped: packs a `column`'s children.

---Box paint for `rect`, `row`, `column` and every surface role.
---[docs](https://anasgets111.github.io/mantle/guide/paint.html#box-properties)
---@class BoxBase
---@field background? Color|Gradient|Bound Absent draws nothing, unlike an explicit transparent `"#00000000"`. A gradient snaps under `animate`.
---@field mask? Mask|Bound Multiplies the alpha of this node and its subtree (ADR-0255). Cut to the box, or to `radius` under `clip = "rounded"`. Hit-testing and `behind_blur` ignore it.
---@field radius? number|Corners|Bound `[0, 8192]`, default `0`. Corner radius px; a number sets all four corners, a missing corner is `0`. Corners too big for a side shrink together, so `radius = 999` makes a pill or circle. Shadows round by the mean corner.
---@field corner_shape? "round"|"scoop"|Bound Default `"round"`. `"scoop"` cuts each corner inward as a quarter circle centred on the corner point; fill, clip, glass, shadow and the `behind_blur` region follow.
---@field border_color? Color|BorderColors|Bound A string sets all four edges; a missing edge has none. An edge draws only with both a colour and a width.
---@field border_width? number|Edges|Bound `[0, 8192]`, default `0`. Px per edge; a number sets all four, a missing edge is `0`. Borders draw inside the box and take no layout space.
---@field behind_blur? boolean|Bound Default `false`. Ask the compositor to blur the desktop behind this box, `ext-background-effect-v1` (ADR-0195). Never inferred from a translucent background. Silently nothing without compositor support; strength is the compositor's.
---@field backdrop_blur? number|Bound `[0, 8192]`, default `0`. Gaussian sigma in px over what this surface already painted under the box, CSS `backdrop-filter` (ADR-0256). Never sees the desktop; cut to `radius`/`corner_shape`.
---@field shadow_mode? "box"|"content"|Bound Default `"box"`. `"box"`: CSS `box-shadow` of the box shape, not drawn under the box. `"content"`: CSS `drop-shadow` of everything painted (ADR-0260).
---@field clip? "box"|"rounded"|"none"|Bound Default `"box"`. `"box"`: children cut to the rectangle. `"rounded"` also cuts to `radius`, at the cost of an offscreen pass. `"none"` leaves children on the parent's clip (ADR-0257).

---One styled stretch of `text.content` (ADR-0104). A notification body's text spans fit as-is;
---drop image spans, which have no `text` and are refused.
---@class TextRun
---@field text string Empty runs are skipped.
---@field bold? boolean Uses the family's bold face when fontconfig has one.
---@field italic? boolean Uses the family's italic face when fontconfig has one.
---@field underline? boolean Underline in the run's colour.
---@field color? Color Overrides the node's `foreground`.
---@field href? string Passed to the node's `on_link` when clicked; never opened by the engine (ADR-0106).
---@field kind? "text" A notification text span's, so one passes through.
---@field [string] "no such property"

---`image.transition`. Unknown keys are refused.
---@class Transition
---@field duration number Required, ms `[1, 60000]`.
---@field easing? Easing Default `"in_out_quad"`; drives `u_progress`.
---@field shader? string Absolute `.frag` path replacing the built-in dissolve, e.g. `mantle.config_dir .. "/shaders/wipe.frag"` (ADR-0184). Recompiled when the file changes.
--- Shader contract. The engine prepends `#version 300 es`, `highp` precision, its declarations and `#line 1`; write `void main()`:
--- - `v_uv`: box coordinates `0..1`, top-left origin, y down.
--- - `u_progress`: eased progress, clamped to `0..1`. `u_size`: node size in logical px.
--- - `mantle_from(uv)`, `mantle_to(uv)`: outgoing and incoming pictures, premultiplied and already placed by `fit`; transparent outside the picture.
--- - `u_from_rect`, `u_to_rect`: each picture's `(x, y, w, h)` in box fractions (may exceed `0..1` under `"cover"`).
--- - Output: premultiplied RGBA in `fragColor`, same colour space as the inputs. The engine applies `opacity` after.
--- - Names starting `u_` or `mantle_` are reserved. A shader that fails to compile or link, or declares a uniform other than `float`/`vec2`-`vec4` or an array of one, logs once and falls back to the dissolve. A shader that hangs the GPU hangs the session.
---@field params? table<string, number|number[]> Uniform values by name: a finite number for `float`, a list of up to 4096 for `vec2`-`vec4` or an array of either, flattened. Missing uniforms are `0`; unknown names are ignored. Refused without `shader`.
---@field [string] "no such property"

---@alias RectAnimations { accessible_name?: Animation, align_h?: Animation, align_v?: Animation, backdrop_blur?: Animation, background?: Animation, behind_blur?: Animation, border_color?: Animation, border_width?: Animation, children?: Animation, clip?: Animation, content_blur?: Animation, corner_shape?: Animation, cursor?: Animation, focus_ring?: Animation, focused?: Animation, geometry?: Animation, height?: Animation, hittable?: Animation, hover?: Animation, id?: Animation, margin?: Animation, mask?: Animation, max_height?: Animation, max_width?: Animation, min_height?: Animation, min_width?: Animation, on_click?: Animation, on_drag?: Animation, on_hover?: Animation, on_wheel?: Animation, opacity?: Animation, origin?: Animation, padding?: Animation, radius?: Animation, rotate?: Animation, scale?: Animation, shadow_blur?: Animation, shadow_color?: Animation, shadow_mode?: Animation, shadow_offset?: Animation, shadow_spread?: Animation, submit?: Animation, translate?: Animation, visible?: Animation, width?: Animation, exit?: Exit, move?: MoveAnimation, [string]: "no such property" }
---@class RectProps: NodeBase, PlacedBase, BoxBase
---@field animate? RectAnimations|Bound Tween named properties to each newly resolved value without running Lua (ADR-0145). `move` eases a matched node to its new parent-relative layout position; an ancestor that shifts needs its own `move`. `exit` runs after removal. Only a node already on screen animates, unless an entry has `from`.
---@field children? Node[]|Bound Stacked in order: later children paint over earlier ones. At most 10000; a `nil` or `false` entry is an error.

---@alias RowAnimations { accessible_name?: Animation, align_h?: Animation, align_v?: Animation, backdrop_blur?: Animation, background?: Animation, behind_blur?: Animation, border_color?: Animation, border_width?: Animation, children?: Animation, clip?: Animation, content_blur?: Animation, corner_shape?: Animation, cursor?: Animation, focus_ring?: Animation, focused?: Animation, geometry?: Animation, height?: Animation, hittable?: Animation, hover?: Animation, id?: Animation, margin?: Animation, mask?: Animation, max_height?: Animation, max_width?: Animation, min_height?: Animation, min_width?: Animation, on_click?: Animation, on_drag?: Animation, on_hover?: Animation, on_wheel?: Animation, opacity?: Animation, origin?: Animation, padding?: Animation, radius?: Animation, rotate?: Animation, scale?: Animation, scroll?: Animation, shadow_blur?: Animation, shadow_color?: Animation, shadow_mode?: Animation, shadow_offset?: Animation, shadow_spread?: Animation, spacing?: Animation, submit?: Animation, translate?: Animation, visible?: Animation, width?: Animation, exit?: Exit, move?: MoveAnimation, [string]: "no such property" }
---@class RowProps: NodeBase, PlacedBase, BoxBase
---@field animate? RowAnimations|Bound Tween named properties to each newly resolved value without running Lua (ADR-0145). `move` eases a matched node to its new parent-relative layout position; an ancestor that shifts needs its own `move`. `exit` runs after removal. Only a node already on screen animates, unless an entry has `from`.
---@field children? Node[]|Bound Laid out in order along the main axis, at most 10000; a `nil` or `false` entry is an error.
---@field spacing? number|Bound Default `0`. Px between visible children; negative values overlap them. Not range-checked.
---@field scroll? Bound A `scroll(name)` signal; makes this a scrolling viewport along its main axis.

---@alias ColumnAnimations { accessible_name?: Animation, align_h?: Animation, align_v?: Animation, backdrop_blur?: Animation, background?: Animation, behind_blur?: Animation, border_color?: Animation, border_width?: Animation, children?: Animation, clip?: Animation, content_blur?: Animation, corner_shape?: Animation, cursor?: Animation, focus_ring?: Animation, focused?: Animation, geometry?: Animation, height?: Animation, hittable?: Animation, hover?: Animation, id?: Animation, margin?: Animation, mask?: Animation, max_height?: Animation, max_width?: Animation, min_height?: Animation, min_width?: Animation, on_click?: Animation, on_drag?: Animation, on_hover?: Animation, on_wheel?: Animation, opacity?: Animation, origin?: Animation, padding?: Animation, radius?: Animation, rotate?: Animation, scale?: Animation, scroll?: Animation, shadow_blur?: Animation, shadow_color?: Animation, shadow_mode?: Animation, shadow_offset?: Animation, shadow_spread?: Animation, spacing?: Animation, submit?: Animation, translate?: Animation, visible?: Animation, width?: Animation, exit?: Exit, move?: MoveAnimation, [string]: "no such property" }
---@class ColumnProps: NodeBase, PlacedBase, BoxBase
---@field animate? ColumnAnimations|Bound Tween named properties to each newly resolved value without running Lua (ADR-0145). `move` eases a matched node to its new parent-relative layout position; an ancestor that shifts needs its own `move`. `exit` runs after removal. Only a node already on screen animates, unless an entry has `from`.
---@field children? Node[]|Bound Laid out in order along the main axis, at most 10000; a `nil` or `false` entry is an error.
---@field spacing? number|Bound Default `0`. Px between visible children; negative values overlap them. Not range-checked.
---@field scroll? Bound A `scroll(name)` signal; makes this a scrolling viewport along its main axis.

---@alias TextAnimations { accessible_name?: Animation, align_h?: Animation, align_v?: Animation, content?: Animation, content_blur?: Animation, cursor?: Animation, elide?: Animation, elided?: Animation, focus_ring?: Animation, focused?: Animation, font?: Animation, font_size?: Animation, font_variations?: Animation, font_weight?: Animation, foreground?: Animation, geometry?: Animation, height?: Animation, hittable?: Animation, hover?: Animation, id?: Animation, italic?: Animation, letter_spacing?: Animation, line_height?: Animation, margin?: Animation, max_height?: Animation, max_lines?: Animation, max_width?: Animation, min_height?: Animation, min_width?: Animation, on_click?: Animation, on_drag?: Animation, on_hover?: Animation, on_link?: Animation, on_wheel?: Animation, opacity?: Animation, origin?: Animation, padding?: Animation, rotate?: Animation, scale?: Animation, shadow_blur?: Animation, shadow_color?: Animation, shadow_offset?: Animation, shadow_spread?: Animation, submit?: Animation, text_align?: Animation, translate?: Animation, visible?: Animation, width?: Animation, wrap?: Animation, exit?: Exit, move?: MoveAnimation, [string]: "no such property" }
---@class TextProps: NodeBase, PlacedBase
---@field animate? TextAnimations|Bound Tween named properties to each newly resolved value without running Lua (ADR-0145). `move` eases a matched node to its new parent-relative layout position; an ancestor that shifts needs its own `move`. `exit` runs after removal. Only a node already on screen animates, unless an entry has `from`.
---@field content? string|TextRun[]|Bound Default `""`. A string, or up to 10000 runs, drawn as one paragraph.
---@field font? string|Bound Default: the `fonts` chain. Family placed before the `fonts` chain (ADR-0144). `""` raises; an unknown family falls back to the chain.
---@field font_size? number|Bound `[1, 8192]`, default `12`. Text size in logical pixels.
---@field line_height? number|Bound `[0.1, 10]`, default `1.2`. Line height as a multiple of `font_size`.
---@field letter_spacing? number|Bound `[-100, 100]`, default `0`. Extra space between characters in logical pixels. Negative values tighten text.
---@field font_weight? number|Bound `[1, 1000]`, default `400`. Font weight from 1 to 1000. A run with `bold = true` uses weight 700.
---@field italic? boolean|Bound Default `false`. Use the family's italic face when available. A run with `italic = true` stays italic.
---@field font_variations? table<string, number>|Bound Default `{}`. OpenType variation axes by 4-character tag, as CSS `font-variation-settings`: `{ FILL = 1, GRAD = -25, opsz = 24 }`. Values clamp to each face's range; axes a face lacks are ignored. An explicit `wght` overrides `font_weight` and bold runs. Changes snap; `animate` does not tween it.
---@field foreground? Color|Bound Default `"#FFFFFF"`. A run's `color` overrides it.
---@field text_align? "start"|"center"|"end"|Bound Default `"start"`. Aligns lines inside the node's own box; `"start"`/`"end"` follow each line's reading direction (ADR-0211). Matters only when the box is wider than the text.
---@field wrap? "none"|"word"|Bound Default `"none"`. `"word"` breaks at words, mid-word when one word is too wide. Needs a bounded width (`width`, `"fill"` or a stretched cross axis).
---@field max_lines? number|Bound Default `0`. Line cap under `wrap = "word"`; `0` is unlimited, a negative value is refused. Ignored without `wrap`.
---@field elide? "none"|"end"|Bound Default `"none"`. `"end"` ends an over-long line with an ellipsis; under `wrap` it applies to the last kept line.
---@field elided? Bound An `elided(name)` signal; layout writes whether `elide` or `max_lines` removed content.
---@field on_link? fun(href: string) Click on a run with an `href` (ADR-0106); the engine never opens it. Takes the click from any `on_click`, the text's own included; plain words pass it on.

---@alias IconAnimations { accessible_name?: Animation, align_h?: Animation, align_v?: Animation, content_blur?: Animation, cursor?: Animation, focus_ring?: Animation, focused?: Animation, foreground?: Animation, geometry?: Animation, height?: Animation, hittable?: Animation, hover?: Animation, id?: Animation, margin?: Animation, max_height?: Animation, max_width?: Animation, min_height?: Animation, min_width?: Animation, name?: Animation, on_click?: Animation, on_drag?: Animation, on_hover?: Animation, on_wheel?: Animation, opacity?: Animation, origin?: Animation, padding?: Animation, rotate?: Animation, scale?: Animation, shadow_blur?: Animation, shadow_color?: Animation, shadow_offset?: Animation, shadow_spread?: Animation, size?: Animation, submit?: Animation, translate?: Animation, visible?: Animation, width?: Animation, exit?: Exit, move?: MoveAnimation, [string]: "no such property" }
---@class IconProps: NodeBase, PlacedBase
---@field animate? IconAnimations|Bound Tween named properties to each newly resolved value without running Lua (ADR-0145). `move` eases a matched node to its new parent-relative layout position; an ancestor that shifts needs its own `move`. `exit` runs after removal. Only a node already on screen animates, unless an entry has `from`.
---@field name? string|Bound Default `""`. Icon theme name, or an absolute image path (ADR-0054); `""` draws nothing.
---@field size? number|Bound Default `12`. The box is `size` × `size` px; not range-checked.
---@field foreground? Color|Bound Default: the file's own colours. Colour for the SVG's `currentColor` (CSS `color`), which tints symbolic icons (ADR-0072); a `-symbolic` icon with no `currentColor` is recoloured whole, hard-coded fills included. Full-colour icons ignore it.

---@alias ImageAnimations { accessible_name?: Animation, align_h?: Animation, align_v?: Animation, async?: Animation, content_blur?: Animation, cursor?: Animation, fit?: Animation, focus_ring?: Animation, focused?: Animation, geometry?: Animation, height?: Animation, hittable?: Animation, hover?: Animation, id?: Animation, margin?: Animation, max_height?: Animation, max_width?: Animation, min_height?: Animation, min_width?: Animation, on_click?: Animation, on_drag?: Animation, on_hover?: Animation, on_wheel?: Animation, opacity?: Animation, origin?: Animation, padding?: Animation, retain?: Animation, rotate?: Animation, scale?: Animation, shadow_blur?: Animation, shadow_color?: Animation, shadow_offset?: Animation, shadow_spread?: Animation, source?: Animation, source_blur?: Animation, submit?: Animation, transition?: Animation, translate?: Animation, visible?: Animation, width?: Animation, exit?: Exit, move?: MoveAnimation, [string]: "no such property" }
---@class ImageProps: NodeBase, PlacedBase
---@field animate? ImageAnimations|Bound Tween named properties to each newly resolved value without running Lua (ADR-0145). `move` eases a matched node to its new parent-relative layout position; an ancestor that shifts needs its own `move`. `exit` runs after removal. Only a node already on screen animates, unless an entry has `from`.
---@field source? string|Bound Default `""`. File path, never a theme name; `""` draws nothing. PNG, JPEG, WebP, GIF, SVG or SVGZ; animated GIFs loop (ADR-0233).
---@field fit? "cover"|"contain"|"stretch"|Bound Default `"cover"`. `"cover"` fills the box and crops, `"contain"` fits inside it, `"stretch"` distorts to it. No intrinsic size: set `width`/`height`.
---@field async? boolean|Bound Default `false`. `false` decodes in the frame that first draws it. `true` decodes on a worker and draws nothing until the first decode lands (ADR-0122). A resize keeps drawing the previous size, scaled, until the new size decodes; use it for many or large images.
---@field retain? boolean|Bound Default `false`. Keep drawing the last picture while a new `source` decodes, and on a failed decode (ADR-0180, ADR-0183). Needs `async = true` and a stable `id`.
---@field transition? Transition|Bound Cross-fade from the held picture to a newly decoded `source` (ADR-0181, ADR-0186). Implies `retain`; needs `async = true` and a stable `id`. The first picture appears without one.
---@field source_blur? number|Bound `[0, 8192]`, default `0`. Blur sigma in px (a fast box approximation), applied once at decode (ADR-0240). Runs on the decoding thread, so pair large images with `async`; under `async` a change blanks the image until the re-decode lands, and `retain` does not cover it (same `source`). Animated GIFs ignore it.

---@alias CaptureAnimations { accessible_name?: Animation, align_h?: Animation, align_v?: Animation, content_blur?: Animation, cursor?: Animation, fit?: Animation, focus_ring?: Animation, focused?: Animation, geometry?: Animation, height?: Animation, hittable?: Animation, hover?: Animation, id?: Animation, live?: Animation, margin?: Animation, max_height?: Animation, max_width?: Animation, min_height?: Animation, min_width?: Animation, on_click?: Animation, on_drag?: Animation, on_hover?: Animation, on_wheel?: Animation, opacity?: Animation, origin?: Animation, output?: Animation, padding?: Animation, paint_cursor?: Animation, region?: Animation, rotate?: Animation, scale?: Animation, shadow_blur?: Animation, shadow_color?: Animation, shadow_offset?: Animation, shadow_spread?: Animation, submit?: Animation, translate?: Animation, visible?: Animation, width?: Animation, window?: Animation, exit?: Exit, move?: MoveAnimation, [string]: "no such property" }
---@class CaptureProps: NodeBase, PlacedBase
---@field animate? CaptureAnimations|Bound Tween named properties to each newly resolved value without running Lua (ADR-0145). `move` eases a matched node to its new parent-relative layout position; an ancestor that shifts needs its own `move`. `exit` runs after removal. Only a node already on screen animates, unless an entry has `from`.
---@field output? string|Bound Default `""`. Connector name, e.g. `"DP-1"`; `""` draws nothing. An unknown name draws nothing and warns once. Changing it starts a fresh capture.
---@field window? string|Bound Default `""`. A `mantle.windows` entry's `id`; `""` draws nothing. Currently requires Hyprland's exact toplevel mapping and ext capture protocols. Cannot combine with a nonempty `output` or `region`. A closed window clears its preview.
---@field fit? "cover"|"contain"|"stretch"|Bound Default `"cover"`. As `image.fit`.
---@field live? boolean|number|Bound Default `false`. `false`: capture on show and on each target change. `true`: every frame, one in flight. A number: at most that many fps, `(0, 1000]` (ADR-0263). Hiding the node or unmapping its surface drops the capture; showing starts a fresh one.
---@field region? Rect|Bound `[0, 8192]`, default: the whole output. Part of the output in its logical px, placed by `fit` as the whole frame. Every key is required and in that range; the size is non-zero.
---@field paint_cursor? boolean|Bound Default `false`. Include the pointer in the frame.

---@alias ShaderAnimations { accessible_name?: Animation, align_h?: Animation, align_v?: Animation, content_blur?: Animation, cursor?: Animation, focus_ring?: Animation, focused?: Animation, geometry?: Animation, height?: Animation, hittable?: Animation, hover?: Animation, id?: Animation, margin?: Animation, max_height?: Animation, max_width?: Animation, min_height?: Animation, min_width?: Animation, on_click?: Animation, on_drag?: Animation, on_hover?: Animation, on_wheel?: Animation, opacity?: Animation, origin?: Animation, padding?: Animation, params?: Animation, progress?: Animation, rotate?: Animation, scale?: Animation, shadow_blur?: Animation, shadow_color?: Animation, shadow_offset?: Animation, shadow_spread?: Animation, source?: Animation, submit?: Animation, translate?: Animation, visible?: Animation, width?: Animation, exit?: Exit, move?: MoveAnimation, [string]: "no such property" }
---@class ShaderProps: NodeBase, PlacedBase
---@field animate? ShaderAnimations|Bound Tween named properties to each newly resolved value without running Lua (ADR-0145). `move` eases a matched node to its new parent-relative layout position; an ancestor that shifts needs its own `move`. `exit` runs after removal. Only a node already on screen animates, unless an entry has `from`.
---@field source? string|Bound Default `""`. Absolute `.frag` path; relative is refused, `""` draws nothing. Saving the file recompiles it; one that fails to build logs once and draws nothing.
---@field progress? number|Bound `[-8192, 8192]`, default `0`. `u_progress`. There is no clock uniform: animate this for motion; the wide range lets a spring overshoot.
---@field params? table<string, number|number[]>|Bound Default `{}`. Uniforms by name: a finite number for `float`, a list of up to 4096 for `vec2`-`vec4` or an array of either, flattened. Missing ones are `0`. Not tweened.

---@alias ListAnimations { accessible_name?: Animation, align_h?: Animation, align_v?: Animation, content_blur?: Animation, cursor?: Animation, direction?: Animation, focus_ring?: Animation, focused?: Animation, geometry?: Animation, height?: Animation, hittable?: Animation, hover?: Animation, id?: Animation, itemfn?: Animation, key?: Animation, limit?: Animation, margin?: Animation, max_height?: Animation, max_width?: Animation, min_height?: Animation, min_width?: Animation, on_click?: Animation, on_drag?: Animation, on_hover?: Animation, on_wheel?: Animation, opacity?: Animation, origin?: Animation, padding?: Animation, rotate?: Animation, scale?: Animation, scroll?: Animation, shadow_blur?: Animation, shadow_color?: Animation, shadow_offset?: Animation, shadow_spread?: Animation, source?: Animation, spacing?: Animation, submit?: Animation, translate?: Animation, visible?: Animation, width?: Animation, exit?: Exit, move?: MoveAnimation, [string]: "no such property" }
---@class ListProps: NodeBase, PlacedBase
---@field animate? ListAnimations|Bound Tween named properties to each newly resolved value without running Lua (ADR-0145). `move` eases a matched node to its new parent-relative layout position; an ancestor that shifts needs its own `move`. `exit` runs after removal. Only a node already on screen animates, unless an entry has `from`.
---@field source? any[]|Bound Default: empty. Array; bind a signal to rebuild on change. Missing or `nil` (a capability before its first push) is an empty list; a `nil` hole ends it. More than 10000 items without `limit` is an error.
---@field itemfn fun(item: any): Node Required. Builds a node for every built item, visible or not.
---@field key? fun(item: any): string Unique UTF-8 key per item; replaces the node's `id`. Duplicates are refused. Without it items match by position.
---@field limit? integer|Bound Build at most this many items; above 10000 acts as 10000, `0` builds none.
---@field direction? "vertical"|"horizontal"|Bound Default `"vertical"`. Lays out as a `column` or a `row`.
---@field spacing? number|Bound Default `0`. Px between visible items along `direction`; negative values overlap them.
---@field scroll? Bound A `scroll(name)` signal; makes this a scrolling viewport along `direction`.

---@alias TextfieldAnimations { accessible_name?: Animation, align_h?: Animation, align_v?: Animation, autofocus?: Animation, content_blur?: Animation, cursor?: Animation, focus_ring?: Animation, focus_target?: Animation, focused?: Animation, font_size?: Animation, foreground?: Animation, geometry?: Animation, height?: Animation, hittable?: Animation, hover?: Animation, id?: Animation, margin?: Animation, mask_character?: Animation, max_height?: Animation, max_width?: Animation, min_height?: Animation, min_width?: Animation, on_cancel?: Animation, on_change?: Animation, on_click?: Animation, on_drag?: Animation, on_hover?: Animation, on_navigate?: Animation, on_submit?: Animation, on_wheel?: Animation, opacity?: Animation, origin?: Animation, padding?: Animation, placeholder?: Animation, rotate?: Animation, scale?: Animation, secure_submit?: Animation, shadow_blur?: Animation, shadow_color?: Animation, shadow_offset?: Animation, shadow_spread?: Animation, submit?: Animation, text_align?: Animation, translate?: Animation, visible?: Animation, width?: Animation, exit?: Exit, move?: MoveAnimation, [string]: "no such property" }
---@class TextfieldProps: NodeBase, PlacedBase
---@field animate? TextfieldAnimations|Bound Tween named properties to each newly resolved value without running Lua (ADR-0145). `move` eases a matched node to its new parent-relative layout position; an ancestor that shifts needs its own `move`. `exit` runs after removal. Only a node already on screen animates, unless an entry has `from`.
---@field focus_target? FocusHandle A `focus_target(name)` handle. An `on_click` can call `:request()` to return keys after its state change; the field must be visible on that click's keyboard-focused surface or a popup under it. Any other value fails the pass.
---@field placeholder? string|Bound Default `""`. Shown while the field is empty, focused or not (ADR-0135). Never submitted.
---@field font_size? number|Bound `[1, 8192]`, default `12`. Size of the text and placeholder.
---@field foreground? Color|Bound Default `"#FFFFFF"`. Colour of the text and placeholder.
---@field text_align? "start"|"center"|"end"|Bound Default `"start"`. Aligns the text inside the field's box.
---@field autofocus? boolean|Bound Default `false`. Plain fields only: take the keyboard, empty, when the surface gets it or the field appears, calling `on_change("")`. The first in document order wins; never steals from a field already typing or one a press just left (ADR-0112).
---@field on_change? fun(text: string) Full text after every edit.
---@field on_submit? fun(text: string) Enter with the full text; the field stays focused and clears. Never fires on a `secure_submit` field.
---@field on_cancel? fun(cleared: boolean) Escape; `cleared` says whether it removed text. A plain field clears (firing `on_change("")` only if there was text), gives up focus, then calls this. A `secure_submit` field scrubs and stays armed. Without it Escape clears and keeps focus (ADR-0102).
---@field on_navigate? fun(key: "up"|"down"|"left"|"right"|"page_up"|"page_down"|"tab"|"backtab") Keys a single-line field does not use, for moving a list selection; repeats while held. Tab and Shift+Tab reach this handler only when fewer than two controls can take focus. `"left"`/`"right"` only when the caret cannot move that way and Shift is up (ADR-0236).
---@field secure_submit? { capability: string, action: string, name?: string, [string]: "no such property" }|Bound Native target for the secret: `lock`/`authenticate`, `polkit`/`authenticate`, `network`/`connect`, `secrets`/`store` with a `name`, or `bluetooth`/`pair` with the request id and MAC in `name`. Makes the field masked.
---@field mask_character? string|Bound Default `"•"`. Drawn per typed character in a `secure_submit` field. Only the first character counts; `""` hides the length.

---@alias PathAnimations { accessible_name?: Animation, align_h?: Animation, align_v?: Animation, commands?: Animation, content_blur?: Animation, cursor?: Animation, fill?: Animation, focus_ring?: Animation, focused?: Animation, geometry?: Animation, height?: Animation, hittable?: Animation, hover?: Animation, id?: Animation, margin?: Animation, max_height?: Animation, max_width?: Animation, min_height?: Animation, min_width?: Animation, on_click?: Animation, on_drag?: Animation, on_hover?: Animation, on_wheel?: Animation, opacity?: Animation, origin?: Animation, padding?: Animation, rotate?: Animation, scale?: Animation, shadow_blur?: Animation, shadow_color?: Animation, shadow_offset?: Animation, shadow_spread?: Animation, stroke?: Animation, stroke_width?: Animation, submit?: Animation, translate?: Animation, visible?: Animation, width?: Animation, exit?: Exit, move?: MoveAnimation, [string]: "no such property" }
---@class PathProps: NodeBase, PlacedBase
---@field animate? PathAnimations|Bound Tween named properties to each newly resolved value without running Lua (ADR-0145). `move` eases a matched node to its new parent-relative layout position; an ancestor that shifts needs its own `move`. `exit` runs after removal. Only a node already on screen animates, unless an entry has `from`.
---@field commands? PathCommand[]|Bound Default `{}`. Up to 4096 commands. Each has op M/L/Q/C/A/Z and points containing 2/2/4/6/5/0 numbers. Begin each subpath with M or A. Coordinates are in [-8192, 8192]; arc angles need only be finite.
---@field fill? Color|Gradient|Bound Fill colour or gradient across the node box. Open subpaths close for filling.
---@field stroke? Color|Gradient|Bound Stroke colour or gradient across the node box. Butt caps and miter joins.
---@field stroke_width? number|Bound `[0, 8192]`, default `1`. Stroke width in logical pixels; centered on the path.

---[docs](https://anasgets111.github.io/mantle/nodes/rect.html)
---@param props RectProps
---@return Node
function rect(props) end

---[docs](https://anasgets111.github.io/mantle/nodes/row-column.html)
---@param props RowProps
---@return Node
function row(props) end

---[docs](https://anasgets111.github.io/mantle/nodes/row-column.html)
---@param props ColumnProps
---@return Node
function column(props) end

---[docs](https://anasgets111.github.io/mantle/nodes/text.html)
---@param props TextProps
---@return Node
function text(props) end

---[docs](https://anasgets111.github.io/mantle/nodes/icon.html)
---@param props IconProps
---@return Node
function icon(props) end

---[docs](https://anasgets111.github.io/mantle/nodes/image.html)
---@param props ImageProps
---@return Node
function image(props) end

---Preview of one output or window (ADR-0248). No intrinsic size: without `width`/`height` it draws nothing.
---[docs](https://anasgets111.github.io/mantle/nodes/capture.html)
---@param props CaptureProps
---@return Node
function capture(props) end

---A config fragment shader over the node's box, with no input textures (ADR-0253). No intrinsic size; without a pointer handler it is transparent to the pointer. Reads `v_uv`, `u_size` and `u_progress` as in `Transition.shader`, writes premultiplied `fragColor`; `opacity`, `shadow_*` and `content_blur` apply.
---[docs](https://anasgets111.github.io/mantle/nodes/shader.html)
---@param props ShaderProps
---@return Node
function shader(props) end

---[docs](https://anasgets111.github.io/mantle/nodes/list.html)
---@param props ListProps
---@return Node
function list(props) end

---Single-line text input. Plain fields read `wl_keyboard` and compose through text-input-v3 when available on their keyboard-focused surface. With `secure_submit` it is masked: keys never reach Lua and go to the capability (ADR-0005, ADR-0092). Otherwise `on_change` or `on_submit` makes it plain; with neither it never takes focus. A press focuses it; the surface needs `keyboard_interactivity`. The draft lives as long as the node; losing focus keeps it (ADR-0108). Intrinsic height is one line of `font_size`; `width` has none, so set it.
---[docs](https://anasgets111.github.io/mantle/nodes/textfield.html)
---@param props TextfieldProps
---@return Node
function textfield(props) end

---A vector path in node-local logical pixels. Set width and height; there is no intrinsic size.
---[docs](https://anasgets111.github.io/mantle/nodes/path.html)
---@param props PathProps
---@return Node
function path(props) end
