//! `docs/capabilities/<name>.md`: the Markdown page for one capability, from the same schemas the
//! Lua stubs walk.

use schemars::Schema;

use super::{action_list, const_enum, enum_strings, fields, one_line, payload_class, unlink};

/// Splits `docs/capabilities/intro/<name>.md`: prose above it opens the page, prose below it
/// (How do I…, Gotchas, See also) follows the generated tables.
const REFERENCE_MARKER: &str = "<!-- reference -->";

/// `docs/capabilities/<name>.md`: the roster blurb, the hand-written `intro`, then the same
/// payload and action schemas `render` walks, as Markdown tables.
pub(super) fn render_page(capability: &str, payload: &Schema, actions: Option<&Schema>, intro: &str) -> String {
    let (intro, outro) = intro.split_once(REFERENCE_MARKER).unwrap_or((intro, ""));
    let blurb = shared::Capability::from_name(capability).expect("a rostered capability").blurb();
    let class = payload_class(payload);
    let payload = payload.as_value();
    let actions = actions.map(Schema::as_value);
    let mut out = format!(
        "<!-- GENERATED by `supervisor/src/stubs.rs` from the Rust types and `intro/{capability}.md`. Do not \
         edit: run `just stubs`. -->\n\n# {capability}\n\n{blurb}\n"
    );
    for section in [intro.trim(), "## State"].into_iter().filter(|section| !section.is_empty()) {
        out.push_str(&format!("\n{section}\n"));
    }
    out.push_str(&format!(
        "\n`mantle.{capability}:get()` returns `{class}`, `nil` before the first push. A field marked `?` may be \
         absent.\n"
    ));
    render_table(payload, &mut out);
    let payload_defs = payload.get("$defs").and_then(|d| d.as_object()).cloned().unwrap_or_default();
    for (name, body) in &payload_defs {
        out.push_str(&format!("\n### `{name}`\n"));
        render_table(body, &mut out);
    }
    out.push_str("\n## Actions\n\n");
    match actions {
        Some(actions) => {
            out.push_str(&format!(
                "Call each as `mantle.{capability}:<action>(arguments...)`; `?` marks an argument you may omit.\n"
            ));
            if let Some(description) = actions.get("description").and_then(|d| d.as_str()) {
                out.push_str(&format!("\n{}\n", prose(description)));
            }
            out.push_str("\n| Action | Arguments | Description |\n| --- | --- | --- |\n");
            for (name, arguments, description) in action_list(actions) {
                let arguments =
                    if arguments.is_empty() { String::new() } else { format!("`{}`", arguments.join(", ")) };
                out.push_str(&format!("| `{name}` | {} | {} |\n", cell(&arguments), cell(description.trim())));
            }
            for (name, body) in actions.get("$defs").and_then(|d| d.as_object()).into_iter().flatten() {
                if !payload_defs.contains_key(name) {
                    out.push_str(&format!("\n### `{name}`\n"));
                    render_table(body, &mut out);
                }
            }
        }
        None => out.push_str("None: read-only, so any method but `get`, `map` and `on_change` raises.\n"),
    }
    let outro = outro.trim();
    if !outro.is_empty() {
        out.push_str(&format!("\n{outro}\n"));
    }
    let module = format!("supervisor/src/capabilities/{capability}");
    let source = if std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join(&module).is_dir() {
        format!("{module}/")
    } else {
        format!("{module}.rs")
    };
    out.push_str(&format!("\nSource: [`{source}`](../../{source})\n"));
    out
}

/// A schema's description, then its string values or its fields as a table.
fn render_table(body: &serde_json::Value, out: &mut String) {
    if let Some(description) = body.get("description").and_then(|d| d.as_str()) {
        out.push_str(&format!("\n{}\n", prose(description)));
    }
    if body.get("properties").is_none()
        && body.get("oneOf").is_none()
        && let Some(values) = enum_strings(body)
    {
        let values: Vec<String> = values.iter().map(|v| format!("`\"{v}\"`")).collect();
        out.push_str(&format!("\nOne of {}.\n", values.join(", ")));
        return;
    }
    if body.get("properties").is_none()
        && let Some(variants) = const_enum(body)
    {
        out.push_str("\n| Value | Description |\n| --- | --- |\n");
        for (variant, description) in variants {
            out.push_str(&format!(
                "| `\"{variant}\"` | {} |\n",
                cell(one_line(description.map(serde_json::Value::from).as_ref()).trim())
            ));
        }
        return;
    }
    out.push_str("\n| Field | Type | Description |\n| --- | --- | --- |\n");
    for (field, (type_name, optional, description)) in fields(body) {
        let marker = if optional { "?" } else { "" };
        out.push_str(&format!("| `{field}{marker}` | `{}` | {} |\n", cell(&type_name), cell(description.trim())));
    }
}

/// A doc comment as Markdown prose: plain code spans, and no `(ADR-NNNN)` pointers, which are history.
fn prose(text: &str) -> String {
    regex_lite::Regex::new(r" \(ADR-\d+(, ADR-\d+)*\)")
        .expect("a valid pattern")
        .replace_all(&unlink(text), "")
        .into_owned()
}

/// A Markdown table cell: GFM splits on `|` even inside a code span.
fn cell(text: &str) -> String {
    prose(text).replace('|', "\\|")
}
